<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'created_at' => '2021-10-20 02:36:38',
                'description' => '',
                'details' => NULL,
                'display_name_plural' => 'Users',
                'display_name_singular' => 'User',
                'generate_permissions' => '1',
                'icon' => 'voyager-person',
                'id' => '1',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'name' => 'users',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'server_side' => '0',
                'slug' => 'users',
                'updated_at' => '2021-10-20 02:36:38',
            ),
            1 => 
            array (
                'controller' => '',
                'created_at' => '2021-10-20 02:36:38',
                'description' => '',
                'details' => NULL,
                'display_name_plural' => 'Menus',
                'display_name_singular' => 'Menu',
                'generate_permissions' => '1',
                'icon' => 'voyager-list',
                'id' => '2',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'name' => 'menus',
                'policy_name' => NULL,
                'server_side' => '0',
                'slug' => 'menus',
                'updated_at' => '2021-10-20 02:36:38',
            ),
            2 => 
            array (
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerRoleController',
                'created_at' => '2021-10-20 02:36:38',
                'description' => '',
                'details' => NULL,
                'display_name_plural' => 'Roles',
                'display_name_singular' => 'Role',
                'generate_permissions' => '1',
                'icon' => 'voyager-lock',
                'id' => '3',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'name' => 'roles',
                'policy_name' => NULL,
                'server_side' => '0',
                'slug' => 'roles',
                'updated_at' => '2021-10-20 02:36:38',
            ),
            3 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-10-20 03:05:37',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Categories',
                'display_name_singular' => 'Category',
                'generate_permissions' => '1',
                'icon' => 'fas fa-boxes',
                'id' => '4',
                'model_name' => 'App\\Models\\Category',
                'name' => 'categories',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'categories',
                'updated_at' => '2022-01-15 16:32:00',
            ),
            4 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-10-20 03:23:00',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Audits',
                'display_name_singular' => 'Audit',
                'generate_permissions' => '1',
                'icon' => 'fas fa-clipboard-list',
                'id' => '6',
                'model_name' => 'App\\Models\\Audit',
                'name' => 'audits',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'audits',
                'updated_at' => '2021-10-20 03:25:27',
            ),
            5 => 
            array (
                'controller' => '\\App\\Http\\Controllers\\Vendor\\Voyager\\ProductController',
                'created_at' => '2021-10-20 03:27:29',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Products',
                'display_name_singular' => 'Product',
                'generate_permissions' => '1',
                'icon' => 'voyager-shop',
                'id' => '7',
                'model_name' => 'App\\Models\\Product',
                'name' => 'products',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'products',
                'updated_at' => '2022-01-21 11:08:21',
            ),
            6 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-10-30 06:23:31',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Customers',
                'display_name_singular' => 'Customer',
                'generate_permissions' => '1',
                'icon' => 'voyager-people',
                'id' => '8',
                'model_name' => 'App\\Models\\Customer',
                'name' => 'customers',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'customers',
                'updated_at' => '2021-10-30 06:24:57',
            ),
            7 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-11-06 13:26:40',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Countries',
                'display_name_singular' => 'Country',
                'generate_permissions' => '1',
                'icon' => 'fa fa-globe',
                'id' => '9',
                'model_name' => 'App\\Models\\Country',
                'name' => 'countries',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'countries',
                'updated_at' => '2021-11-06 13:27:13',
            ),
            8 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-11-06 13:29:43',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Provinces',
                'display_name_singular' => 'Province',
                'generate_permissions' => '1',
                'icon' => 'fa fa-location-arrow',
                'id' => '10',
                'model_name' => 'App\\Models\\Province',
                'name' => 'provinces',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'provinces',
                'updated_at' => '2021-11-06 13:33:24',
            ),
            9 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-11-06 13:34:12',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Cities',
                'display_name_singular' => 'City',
                'generate_permissions' => '1',
                'icon' => 'fa fa-building',
                'id' => '11',
                'model_name' => 'App\\Models\\City',
                'name' => 'cities',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'cities',
                'updated_at' => '2021-11-06 13:35:28',
            ),
            10 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-11-09 02:09:55',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Product Attributes',
                'display_name_singular' => 'Product Attribute',
                'generate_permissions' => '1',
                'icon' => 'fa fa-info',
                'id' => '12',
                'model_name' => 'App\\Models\\ProductAttribute',
                'name' => 'product_attributes',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'product-attributes',
                'updated_at' => '2021-11-09 03:22:48',
            ),
            11 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-11-09 02:32:16',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Attributes',
                'display_name_singular' => 'Attribute',
                'generate_permissions' => '1',
                'icon' => 'voyager-info-circled',
                'id' => '13',
                'model_name' => 'App\\Models\\Attribute',
                'name' => 'attributes',
                'policy_name' => NULL,
                'server_side' => '0',
                'slug' => 'attributes',
                'updated_at' => '2021-11-09 02:33:52',
            ),
            12 => 
            array (
                'controller' => '\\App\\Http\\Controllers\\Vendor\\Voyager\\TransactionController',
                'created_at' => '2021-12-03 07:03:32',
                'description' => NULL,
                'details' => '{"order_column":"updated_at","order_display_column":"updated_at","order_direction":"desc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Transactions',
                'display_name_singular' => 'Transaction',
                'generate_permissions' => '1',
                'icon' => 'fas fa-shopping-cart',
                'id' => '14',
                'model_name' => 'App\\Models\\Transaction',
                'name' => 'transactions',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'transactions',
                'updated_at' => '2021-12-23 14:17:55',
            ),
            13 => 
            array (
                'controller' => NULL,
                'created_at' => '2021-12-22 13:49:44',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'display_name_plural' => 'Permissions',
                'display_name_singular' => 'Permission',
                'generate_permissions' => '1',
                'icon' => 'voyager-lock',
                'id' => '16',
                'model_name' => 'App\\Models\\Permission',
                'name' => 'permissions',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'permissions',
                'updated_at' => '2021-12-22 13:49:44',
            ),
            14 => 
            array (
                'controller' => NULL,
                'created_at' => '2022-01-31 17:24:18',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'display_name_plural' => 'Feedbacks',
                'display_name_singular' => 'Feedback',
                'generate_permissions' => '1',
                'icon' => 'far fa-comments',
                'id' => '17',
                'model_name' => 'App\\Models\\WebsiteFeedback',
                'name' => 'website_feedback',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'website-feedback',
                'updated_at' => '2022-01-31 17:24:18',
            ),
            15 => 
            array (
                'controller' => NULL,
                'created_at' => '2022-01-31 17:27:53',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Sliders',
                'display_name_singular' => 'Slider',
                'generate_permissions' => '1',
                'icon' => 'fas fa-images',
                'id' => '19',
                'model_name' => 'App\\Models\\Slider',
                'name' => 'sliders',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'sliders',
                'updated_at' => '2022-02-02 09:28:44',
            ),
            16 => 
            array (
                'controller' => NULL,
                'created_at' => '2022-01-31 17:34:24',
                'description' => NULL,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'display_name_plural' => 'Homepage Contents',
                'display_name_singular' => 'Homepage Content',
                'generate_permissions' => '1',
                'icon' => 'voyager-home',
                'id' => '20',
                'model_name' => 'App\\Models\\HomepageContent',
                'name' => 'homepage_contents',
                'policy_name' => NULL,
                'server_side' => '1',
                'slug' => 'homepage-contents',
                'updated_at' => '2022-02-02 11:04:22',
            ),
        ));
        
        
    }
}