<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '1',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => '0',
                'field' => 'id',
                'id' => '1',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '1',
                'delete' => '1',
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => '1',
                'field' => 'name',
                'id' => '2',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '1',
                'delete' => '1',
                'details' => NULL,
                'display_name' => 'Email',
                'edit' => '1',
                'field' => 'email',
                'id' => '3',
                'order' => '3',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '1',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Password',
                'edit' => '1',
                'field' => 'password',
                'id' => '4',
                'order' => '4',
                'read' => '0',
                'required' => '1',
                'type' => 'password',
            ),
            4 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '1',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Remember Token',
                'edit' => '0',
                'field' => 'remember_token',
                'id' => '5',
                'order' => '5',
                'read' => '0',
                'required' => '0',
                'type' => 'text',
            ),
            5 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '1',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '6',
                'order' => '6',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            6 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '1',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '7',
                'order' => '7',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            7 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '1',
                'delete' => '1',
                'details' => NULL,
                'display_name' => 'Avatar',
                'edit' => '1',
                'field' => 'avatar',
                'id' => '8',
                'order' => '8',
                'read' => '1',
                'required' => '0',
                'type' => 'image',
            ),
            8 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '1',
                'delete' => '0',
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'display_name' => 'Role',
                'edit' => '1',
                'field' => 'user_belongsto_role_relationship',
                'id' => '9',
                'order' => '10',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            9 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '1',
                'delete' => '0',
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'display_name' => 'voyager::seeders.data_rows.roles',
                'edit' => '1',
                'field' => 'user_belongstomany_role_relationship',
                'id' => '10',
                'order' => '11',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            10 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '1',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Settings',
                'edit' => '0',
                'field' => 'settings',
                'id' => '11',
                'order' => '12',
                'read' => '0',
                'required' => '0',
                'type' => 'hidden',
            ),
            11 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '2',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => '0',
                'field' => 'id',
                'id' => '12',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'number',
            ),
            12 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '2',
                'delete' => '1',
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => '1',
                'field' => 'name',
                'id' => '13',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            13 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '2',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '14',
                'order' => '3',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            14 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '2',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '15',
                'order' => '4',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            15 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '3',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => '0',
                'field' => 'id',
                'id' => '16',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'number',
            ),
            16 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '3',
                'delete' => '1',
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => '1',
                'field' => 'name',
                'id' => '17',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            17 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '3',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '18',
                'order' => '3',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            18 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '3',
                'delete' => '0',
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '19',
                'order' => '4',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            19 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '3',
                'delete' => '1',
                'details' => NULL,
                'display_name' => 'Display Name',
                'edit' => '1',
                'field' => 'display_name',
                'id' => '20',
                'order' => '5',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '1',
                'delete' => '1',
                'details' => NULL,
                'display_name' => 'Role',
                'edit' => '1',
                'field' => 'role_id',
                'id' => '21',
                'order' => '9',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            21 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '4',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '22',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            22 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '4',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => '1',
                'field' => 'name',
                'id' => '23',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            23 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '4',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '24',
                'order' => '3',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            24 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '4',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '25',
                'order' => '4',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            25 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '6',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '26',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            26 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'User Type',
                'edit' => '1',
                'field' => 'user_type',
                'id' => '27',
                'order' => '2',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            27 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'User Id',
                'edit' => '1',
                'field' => 'user_id',
                'id' => '28',
                'order' => '3',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            28 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Event',
                'edit' => '1',
                'field' => 'event',
                'id' => '29',
                'order' => '4',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            29 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Auditable Type',
                'edit' => '1',
                'field' => 'auditable_type',
                'id' => '30',
                'order' => '5',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            30 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Auditable Id',
                'edit' => '1',
                'field' => 'auditable_id',
                'id' => '31',
                'order' => '6',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            31 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Old Values',
                'edit' => '1',
                'field' => 'old_values',
                'id' => '32',
                'order' => '7',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            32 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'New Values',
                'edit' => '1',
                'field' => 'new_values',
                'id' => '33',
                'order' => '8',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            33 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Url',
                'edit' => '1',
                'field' => 'url',
                'id' => '34',
                'order' => '9',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            34 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Ip Address',
                'edit' => '1',
                'field' => 'ip_address',
                'id' => '35',
                'order' => '10',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            35 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'User Agent',
                'edit' => '1',
                'field' => 'user_agent',
                'id' => '36',
                'order' => '11',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            36 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Tags',
                'edit' => '1',
                'field' => 'tags',
                'id' => '37',
                'order' => '12',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            37 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '38',
                'order' => '13',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            38 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '6',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '39',
                'order' => '14',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            39 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '6',
                'delete' => '1',
                'details' => '{"model":"App\\\\Models\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"email","pivot_table":"attributes","pivot":"0","taggable":"0"}',
                'display_name' => 'users',
                'edit' => '1',
                'field' => 'audit_belongsto_user_relationship',
                'id' => '40',
                'order' => '15',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            40 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '4',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Icon Class',
                'edit' => '1',
                'field' => 'icon_class',
                'id' => '41',
                'order' => '3',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            41 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '4',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => '0',
                'field' => 'deleted_at',
                'id' => '42',
                'order' => '6',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            42 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '43',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            43 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Nama Produk',
                'edit' => '1',
                'field' => 'name',
                'id' => '44',
                'order' => '5',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            44 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Detail Produk',
                'edit' => '1',
                'field' => 'description',
                'id' => '45',
                'order' => '6',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            45 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Display Price',
                'edit' => '1',
                'field' => 'display_price',
                'id' => '46',
                'order' => '7',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            46 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Price',
                'edit' => '1',
                'field' => 'price',
                'id' => '47',
                'order' => '8',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            47 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
            'display_name' => 'Weight (Gr)',
                'edit' => '1',
                'field' => 'weight',
                'id' => '48',
                'order' => '9',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            48 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
            'display_name' => 'Dimension Width (mm)',
                'edit' => '1',
                'field' => 'dimension_width',
                'id' => '49',
                'order' => '10',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            49 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
            'display_name' => 'Dimension Height (mm)',
                'edit' => '1',
                'field' => 'dimension_height',
                'id' => '50',
                'order' => '11',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            50 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
            'display_name' => 'Dimension Depth (mm)',
                'edit' => '1',
                'field' => 'dimension_depth',
                'id' => '51',
                'order' => '12',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            51 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '7',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Stock',
                'edit' => '0',
                'field' => 'stock',
                'id' => '52',
                'order' => '13',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            52 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Category Id',
                'edit' => '1',
                'field' => 'category_id',
                'id' => '53',
                'order' => '4',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            53 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '54',
                'order' => '14',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            54 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '55',
                'order' => '16',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            55 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => '0',
                'field' => 'deleted_at',
                'id' => '56',
                'order' => '17',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            56 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{"max":10,"min":0}',
                'display_name' => 'Images',
                'edit' => '1',
                'field' => 'images',
                'id' => '57',
                'order' => '15',
                'read' => '1',
                'required' => '0',
                'type' => 'media_picker',
            ),
            57 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '8',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '58',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            58 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '8',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '1',
                'field' => 'created_at',
                'id' => '59',
                'order' => '10',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            59 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '8',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '60',
                'order' => '2',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            60 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '8',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => '1',
                'field' => 'email',
                'id' => '61',
                'order' => '3',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            61 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '8',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Password',
                'edit' => '1',
                'field' => 'password',
                'id' => '62',
                'order' => '4',
                'read' => '0',
                'required' => '1',
                'type' => 'password',
            ),
            62 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '8',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'First Name',
                'edit' => '1',
                'field' => 'first_name',
                'id' => '63',
                'order' => '5',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            63 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '8',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Last Name',
                'edit' => '1',
                'field' => 'last_name',
                'id' => '64',
                'order' => '6',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            64 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '8',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Phone',
                'edit' => '1',
                'field' => 'phone',
                'id' => '65',
                'order' => '7',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            65 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '8',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Email Verified At',
                'edit' => '1',
                'field' => 'email_verified_at',
                'id' => '66',
                'order' => '8',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            66 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '8',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Phone Verified At',
                'edit' => '1',
                'field' => 'phone_verified_at',
                'id' => '67',
                'order' => '9',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            67 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '9',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '1',
                'field' => 'id',
                'id' => '68',
                'order' => '1',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            68 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '9',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => '1',
                'field' => 'name',
                'id' => '69',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            69 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '9',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '70',
                'order' => '3',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            70 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '9',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '71',
                'order' => '4',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            71 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '10',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '1',
                'field' => 'id',
                'id' => '72',
                'order' => '1',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            72 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '10',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => '1',
                'field' => 'name',
                'id' => '73',
                'order' => '3',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            73 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '10',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Country Id',
                'edit' => '1',
                'field' => 'country_id',
                'id' => '74',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            74 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '10',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '75',
                'order' => '4',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            75 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '10',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '76',
                'order' => '5',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            76 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '10',
                'delete' => '1',
                'details' => '{"model":"App\\\\Models\\\\Country","table":"countries","type":"belongsTo","column":"country_id","key":"id","label":"name","pivot_table":"attributes","pivot":"0","taggable":"0"}',
                'display_name' => 'countries',
                'edit' => '1',
                'field' => 'province_belongsto_country_relationship',
                'id' => '77',
                'order' => '6',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            77 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '11',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '1',
                'field' => 'id',
                'id' => '78',
                'order' => '1',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            78 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '11',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => '1',
                'field' => 'name',
                'id' => '79',
                'order' => '3',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            79 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '11',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Province Id',
                'edit' => '1',
                'field' => 'province_id',
                'id' => '80',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            80 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '11',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '1',
                'field' => 'created_at',
                'id' => '81',
                'order' => '4',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            81 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '11',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '82',
                'order' => '5',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            82 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '11',
                'delete' => '1',
                'details' => '{"model":"App\\\\Models\\\\Province","table":"provinces","type":"belongsTo","column":"province_id","key":"id","label":"name","pivot_table":"attributes","pivot":"0","taggable":"0"}',
                'display_name' => 'provinces',
                'edit' => '1',
                'field' => 'city_belongsto_province_relationship',
                'id' => '83',
                'order' => '6',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            83 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Kode Produk',
                'edit' => '1',
                'field' => 'code',
                'id' => '84',
                'order' => '2',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            84 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '12',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '85',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            85 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '12',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Attribute Id',
                'edit' => '0',
                'field' => 'attribute_id',
                'id' => '86',
                'order' => '3',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            86 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '12',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Value',
                'edit' => '1',
                'field' => 'value',
                'id' => '87',
                'order' => '5',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            87 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '12',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '88',
                'order' => '6',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            88 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '12',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '89',
                'order' => '7',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            89 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '12',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => '0',
                'field' => 'deleted_at',
                'id' => '90',
                'order' => '8',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            90 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{"model":"App\\\\Models\\\\Category","table":"categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"attributes","pivot":"0","taggable":"0"}',
                'display_name' => 'categories',
                'edit' => '1',
                'field' => 'product_belongsto_category_relationship',
                'id' => '91',
                'order' => '3',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            91 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '12',
                'delete' => '1',
                'details' => '{"model":"App\\\\Models\\\\Attribute","table":"attributes","type":"belongsTo","column":"attribute_id","key":"id","label":"name","pivot_table":"attributes","pivot":"0","taggable":"0"}',
                'display_name' => 'attributes',
                'edit' => '1',
                'field' => 'product_attribute_belongsto_attribute_relationship',
                'id' => '92',
                'order' => '4',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            92 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '13',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '93',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            93 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '13',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => '1',
                'field' => 'name',
                'id' => '94',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            94 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '13',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Required',
                'edit' => '1',
                'field' => 'required',
                'id' => '95',
                'order' => '3',
                'read' => '1',
                'required' => '1',
                'type' => 'checkbox',
            ),
            95 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '13',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Options',
                'edit' => '1',
                'field' => 'options',
                'id' => '96',
                'order' => '4',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            96 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '13',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '97',
                'order' => '5',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            97 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '13',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '98',
                'order' => '6',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            98 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '13',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => '0',
                'field' => 'deleted_at',
                'id' => '99',
                'order' => '7',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            99 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '12',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Product Id',
                'edit' => '0',
                'field' => 'product_id',
                'id' => '100',
                'order' => '2',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            100 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '101',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            101 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Uuid',
                'edit' => '1',
                'field' => 'uuid',
                'id' => '102',
                'order' => '11',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            102 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Customer Name',
                'edit' => '1',
                'field' => 'customer_name',
                'id' => '103',
                'order' => '12',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            103 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Customer Email',
                'edit' => '1',
                'field' => 'customer_email',
                'id' => '104',
                'order' => '13',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            104 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Customer Phone',
                'edit' => '1',
                'field' => 'customer_phone',
                'id' => '105',
                'order' => '14',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            105 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Date',
                'edit' => '1',
                'field' => 'date',
                'id' => '106',
                'order' => '15',
                'read' => '1',
                'required' => '1',
                'type' => 'timestamp',
            ),
            106 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Weight',
                'edit' => '1',
                'field' => 'weight',
                'id' => '107',
                'order' => '16',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            107 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Total Price',
                'edit' => '1',
                'field' => 'total_price',
                'id' => '108',
                'order' => '17',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            108 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping Cost',
                'edit' => '1',
                'field' => 'shipping_cost',
                'id' => '109',
                'order' => '18',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            109 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping Multiplier',
                'edit' => '1',
                'field' => 'shipping_multiplier',
                'id' => '110',
                'order' => '19',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            110 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Total Shipping Cost',
                'edit' => '1',
                'field' => 'total_shipping_cost',
                'id' => '111',
                'order' => '20',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            111 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Grand Total',
                'edit' => '1',
                'field' => 'grand_total',
                'id' => '112',
                'order' => '21',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            112 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Discount',
                'edit' => '1',
                'field' => 'discount',
                'id' => '113',
                'order' => '22',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            113 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Admin Id',
                'edit' => '1',
                'field' => 'admin_id',
                'id' => '114',
                'order' => '2',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            114 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Customer Id',
                'edit' => '1',
                'field' => 'customer_id',
                'id' => '115',
                'order' => '3',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            115 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Status Id',
                'edit' => '1',
                'field' => 'status_id',
                'id' => '116',
                'order' => '4',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            116 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping Recipient Name',
                'edit' => '1',
                'field' => 'shipping_recipient_name',
                'id' => '117',
                'order' => '23',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            117 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping Recipient Number',
                'edit' => '1',
                'field' => 'shipping_recipient_number',
                'id' => '118',
                'order' => '24',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            118 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping Address',
                'edit' => '1',
                'field' => 'shipping_address',
                'id' => '119',
                'order' => '25',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            119 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping Postal Code',
                'edit' => '1',
                'field' => 'shipping_postal_code',
                'id' => '120',
                'order' => '26',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            120 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping Country Id',
                'edit' => '1',
                'field' => 'shipping_country_id',
                'id' => '121',
                'order' => '6',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            121 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping Province Id',
                'edit' => '1',
                'field' => 'shipping_province_id',
                'id' => '122',
                'order' => '7',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            122 => 
            array (
                'add' => '1',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Shipping City Id',
                'edit' => '1',
                'field' => 'shipping_city_id',
                'id' => '123',
                'order' => '9',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            123 => 
            array (
                'add' => '0',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '124',
                'order' => '27',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            124 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '125',
                'order' => '28',
                'read' => '1',
                'required' => '0',
                'type' => 'timestamp',
            ),
            125 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '14',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Deleted At',
                'edit' => '0',
                'field' => 'deleted_at',
                'id' => '126',
                'order' => '29',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            126 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{"model":"App\\\\Models\\\\City","table":"cities","type":"belongsTo","column":"shipping_city_id","key":"id","label":"name","pivot_table":"attributes","pivot":"0","taggable":"0"}',
                'display_name' => 'Kota Pengiriman',
                'edit' => '1',
                'field' => 'transaction_belongsto_city_relationship',
                'id' => '127',
                'order' => '10',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            127 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{"model":"App\\\\Models\\\\Province","table":"provinces","type":"belongsTo","column":"shipping_province_id","key":"id","label":"name","pivot_table":"attributes","pivot":"0","taggable":"0"}',
                'display_name' => 'Provinsi Pengiriman',
                'edit' => '1',
                'field' => 'transaction_belongsto_province_relationship',
                'id' => '128',
                'order' => '8',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            128 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{"model":"App\\\\Models\\\\TransactionStatus","table":"transaction_statuses","type":"belongsTo","column":"status_id","key":"id","label":"name","pivot_table":"attributes","pivot":"0","taggable":"0"}',
                'display_name' => 'Status',
                'edit' => '1',
                'field' => 'transaction_belongsto_transaction_status_relationship',
                'id' => '129',
                'order' => '5',
                'read' => '1',
                'required' => '0',
                'type' => 'relationship',
            ),
            129 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '14',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Resi No',
                'edit' => '1',
                'field' => 'resi_no',
                'id' => '130',
                'order' => '9',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            130 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '16',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '131',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            131 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '16',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Key',
                'edit' => '1',
                'field' => 'key',
                'id' => '132',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            132 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '16',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Table Name',
                'edit' => '1',
                'field' => 'table_name',
                'id' => '133',
                'order' => '3',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            133 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '16',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '134',
                'order' => '4',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            134 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '16',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '135',
                'order' => '5',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            135 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '7',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Brand Id',
                'edit' => '1',
                'field' => 'brand_id',
                'id' => '136',
                'order' => '14',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            136 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '17',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '137',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            137 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '17',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Email',
                'edit' => '1',
                'field' => 'email',
                'id' => '138',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            138 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '17',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'First Name',
                'edit' => '1',
                'field' => 'first_name',
                'id' => '139',
                'order' => '3',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            139 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '17',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Last Name',
                'edit' => '1',
                'field' => 'last_name',
                'id' => '140',
                'order' => '4',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            140 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '17',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Phone',
                'edit' => '1',
                'field' => 'phone',
                'id' => '141',
                'order' => '5',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            141 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '17',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Message',
                'edit' => '1',
                'field' => 'message',
                'id' => '142',
                'order' => '6',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            142 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '17',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '143',
                'order' => '7',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            143 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '17',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '144',
                'order' => '8',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            144 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '19',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '145',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            145 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '19',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Title',
                'edit' => '0',
                'field' => 'title',
                'id' => '146',
                'order' => '2',
                'read' => '0',
                'required' => '0',
                'type' => 'text',
            ),
            146 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '19',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Description',
                'edit' => '0',
                'field' => 'description',
                'id' => '147',
                'order' => '3',
                'read' => '0',
                'required' => '0',
                'type' => 'text',
            ),
            147 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '19',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '149',
                'order' => '5',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            148 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '19',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '150',
                'order' => '6',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            149 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '20',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => '0',
                'field' => 'id',
                'id' => '151',
                'order' => '1',
                'read' => '0',
                'required' => '1',
                'type' => 'text',
            ),
            150 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '20',
                'delete' => '1',
                'details' => '{"display":{"id":"homepage_contents__products"}}',
                'display_name' => 'Products',
                'edit' => '1',
                'field' => 'products',
                'id' => '152',
                'order' => '4',
                'read' => '1',
                'required' => '1',
                'type' => 'select_multiple',
            ),
            151 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '20',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Title',
                'edit' => '1',
                'field' => 'title',
                'id' => '153',
                'order' => '3',
                'read' => '1',
                'required' => '0',
                'type' => 'text',
            ),
            152 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '20',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Code',
                'edit' => '1',
                'field' => 'code',
                'id' => '154',
                'order' => '2',
                'read' => '1',
                'required' => '1',
                'type' => 'text',
            ),
            153 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '20',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => '0',
                'field' => 'created_at',
                'id' => '155',
                'order' => '5',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            154 => 
            array (
                'add' => '0',
                'browse' => '0',
                'data_type_id' => '20',
                'delete' => '0',
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => '0',
                'field' => 'updated_at',
                'id' => '156',
                'order' => '6',
                'read' => '0',
                'required' => '0',
                'type' => 'timestamp',
            ),
            155 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '19',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Image',
                'edit' => '1',
                'field' => 'image',
                'id' => '157',
                'order' => '4',
                'read' => '1',
                'required' => '1',
                'type' => 'image',
            ),
            156 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '19',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Order',
                'edit' => '1',
                'field' => 'order',
                'id' => '158',
                'order' => '5',
                'read' => '1',
                'required' => '1',
                'type' => 'number',
            ),
            157 => 
            array (
                'add' => '1',
                'browse' => '1',
                'data_type_id' => '20',
                'delete' => '1',
                'details' => '{}',
                'display_name' => 'Order',
                'edit' => '1',
                'field' => 'order',
                'id' => '159',
                'order' => '5',
                'read' => '1',
                'required' => '1',
                'type' => 'number',
            ),
        ));
        
        
    }
}