<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 10,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 11,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 12,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 13,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2021-10-20 02:36:38',
                'updated_at' => '2021-10-20 02:36:38',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas fa-boxes',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2021-10-20 03:05:37',
                'updated_at' => '2021-10-20 03:05:37',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Audits',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas fa-clipboard-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2021-10-20 03:23:00',
                'updated_at' => '2021-10-20 03:23:25',
                'route' => 'voyager.audits.index',
                'parameters' => 'null',
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Products',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-shop',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2021-10-20 03:27:29',
                'updated_at' => '2021-10-20 03:27:29',
                'route' => 'voyager.products.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 2,
                'title' => 'Gagang Pintu',
                'url' => '/products?category=18',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-10-20 04:13:04',
                'updated_at' => '2022-01-28 10:18:56',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => 'Keran Air',
                'url' => '/products?category=5',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2021-10-20 04:13:14',
                'updated_at' => '2022-01-28 10:20:09',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => 'Tiang Shower',
                'url' => '/products?category=2',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2021-10-20 04:13:24',
                'updated_at' => '2022-01-28 10:50:51',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 3,
                'title' => 'Gagang Pintu',
                'url' => '/products?category=18',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-10-20 04:17:02',
                'updated_at' => '2022-01-28 10:56:09',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 3,
                'title' => 'Keran Air',
                'url' => '/products?category=5',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2021-10-20 04:19:17',
                'updated_at' => '2022-01-28 10:56:09',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 4,
                'title' => 'Akun Saya',
                'url' => '/profile',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2021-10-20 04:20:31',
                'updated_at' => '2022-01-28 10:52:25',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 5,
                'title' => 'Kebijakan Privasi',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 24,
                'created_at' => '2021-10-20 04:21:15',
                'updated_at' => '2021-10-20 04:21:15',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Customers',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 25,
                'created_at' => '2021-10-30 06:23:31',
                'updated_at' => '2021-10-30 06:23:31',
                'route' => 'voyager.customers.index',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Countries',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa fa-globe',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 26,
                'created_at' => '2021-11-06 13:26:40',
                'updated_at' => '2021-11-06 13:26:40',
                'route' => 'voyager.countries.index',
                'parameters' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Provinces',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa fa-location-arrow',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 27,
                'created_at' => '2021-11-06 13:29:43',
                'updated_at' => '2021-11-06 13:33:43',
                'route' => 'voyager.provinces.index',
                'parameters' => 'null',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Cities',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa fa-building',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 28,
                'created_at' => '2021-11-06 13:34:12',
                'updated_at' => '2021-11-06 13:34:12',
                'route' => 'voyager.cities.index',
                'parameters' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Product Attributes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa fa-info',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 29,
                'created_at' => '2021-11-09 02:09:55',
                'updated_at' => '2021-11-09 02:09:55',
                'route' => 'voyager.product-attributes.index',
                'parameters' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Attributes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-info-circled',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 30,
                'created_at' => '2021-11-09 02:32:17',
                'updated_at' => '2021-11-09 02:32:17',
                'route' => 'voyager.attributes.index',
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Transactions',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fas fa-shopping-cart',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 31,
                'created_at' => '2021-12-03 07:03:32',
                'updated_at' => '2021-12-03 07:04:16',
                'route' => 'voyager.transactions.index',
                'parameters' => 'null',
            ),
            27 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Permissions',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 32,
                'created_at' => '2021-12-22 13:49:44',
                'updated_at' => '2021-12-22 13:49:44',
                'route' => 'voyager.permissions.index',
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'menu_id' => 2,
                'title' => 'Produk Lainnya',
                'url' => '/products?category=13',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 33,
                'created_at' => '2022-01-15 16:45:15',
                'updated_at' => '2022-01-28 10:49:42',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 31,
                'menu_id' => 3,
                'title' => 'Tiang Shower',
                'url' => '/products?category=2',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2022-01-15 16:59:03',
                'updated_at' => '2022-01-28 10:56:09',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 32,
                'menu_id' => 3,
                'title' => 'Produk Lainnya',
                'url' => '/products?category=13',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2022-01-15 16:59:12',
                'updated_at' => '2022-01-28 10:56:09',
                'route' => NULL,
                'parameters' => '',
            ),
            31 => 
            array (
                'id' => 33,
                'menu_id' => 3,
                'title' => 'Aksesoris Helm',
                'url' => '/products?category=14',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-01-15 16:59:26',
                'updated_at' => '2022-01-28 10:56:09',
                'route' => NULL,
                'parameters' => '',
            ),
            32 => 
            array (
                'id' => 34,
                'menu_id' => 5,
                'title' => 'Hubungi Kami',
                'url' => '/contact_us',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 34,
                'created_at' => '2022-01-28 11:01:04',
                'updated_at' => '2022-01-28 11:01:35',
                'route' => NULL,
                'parameters' => '',
            ),
            33 => 
            array (
                'id' => 35,
                'menu_id' => 5,
                'title' => 'Tentang Kami',
                'url' => '/about_us',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 35,
                'created_at' => '2022-01-28 11:01:28',
                'updated_at' => '2022-01-28 11:01:28',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}