<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-boat',
                'id' => '1',
                'menu_id' => '1',
                'order' => '1',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.dashboard',
                'target' => '_self',
                'title' => 'Dashboard',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-images',
                'id' => '2',
                'menu_id' => '1',
                'order' => '5',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-person',
                'id' => '3',
                'menu_id' => '1',
                'order' => '3',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-lock',
                'id' => '4',
                'menu_id' => '1',
                'order' => '2',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-tools',
                'id' => '5',
                'menu_id' => '1',
                'order' => '9',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tools',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-list',
                'id' => '6',
                'menu_id' => '1',
                'order' => '10',
                'parameters' => NULL,
                'parent_id' => '5',
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-data',
                'id' => '7',
                'menu_id' => '1',
                'order' => '11',
                'parameters' => NULL,
                'parent_id' => '5',
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-compass',
                'id' => '8',
                'menu_id' => '1',
                'order' => '12',
                'parameters' => NULL,
                'parent_id' => '5',
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-bread',
                'id' => '9',
                'menu_id' => '1',
                'order' => '13',
                'parameters' => NULL,
                'parent_id' => '5',
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 02:36:38',
                'icon_class' => 'voyager-settings',
                'id' => '10',
                'menu_id' => '1',
                'order' => '14',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Settings',
                'updated_at' => '2021-10-20 02:36:38',
                'url' => '',
            ),
            10 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 03:05:37',
                'icon_class' => 'fas fa-boxes',
                'id' => '11',
                'menu_id' => '1',
                'order' => '15',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categories',
                'updated_at' => '2021-10-20 03:05:37',
                'url' => '',
            ),
            11 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-10-20 03:23:00',
                'icon_class' => 'fas fa-clipboard-list',
                'id' => '12',
                'menu_id' => '1',
                'order' => '16',
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.audits.index',
                'target' => '_self',
                'title' => 'Audits',
                'updated_at' => '2021-10-20 03:23:25',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-20 03:27:29',
                'icon_class' => 'voyager-shop',
                'id' => '13',
                'menu_id' => '1',
                'order' => '17',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.products.index',
                'target' => '_self',
                'title' => 'Products',
                'updated_at' => '2021-10-20 03:27:29',
                'url' => '',
            ),
            13 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-10-20 04:13:04',
                'icon_class' => NULL,
                'id' => '14',
                'menu_id' => '2',
                'order' => '1',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Gagang Pintu',
                'updated_at' => '2022-01-28 10:18:56',
                'url' => '/products?category=18',
            ),
            14 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-10-20 04:13:14',
                'icon_class' => NULL,
                'id' => '15',
                'menu_id' => '2',
                'order' => '2',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Keran Air',
                'updated_at' => '2022-01-28 10:20:09',
                'url' => '/products?category=5',
            ),
            15 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-10-20 04:13:24',
                'icon_class' => NULL,
                'id' => '16',
                'menu_id' => '2',
                'order' => '3',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tiang Shower',
                'updated_at' => '2022-01-28 10:50:51',
                'url' => '/products?category=2',
            ),
            16 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-10-20 04:17:02',
                'icon_class' => NULL,
                'id' => '17',
                'menu_id' => '3',
                'order' => '1',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Gagang Pintu',
                'updated_at' => '2022-01-28 10:56:09',
                'url' => '/products?category=18',
            ),
            17 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-10-20 04:19:17',
                'icon_class' => NULL,
                'id' => '18',
                'menu_id' => '3',
                'order' => '2',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Keran Air',
                'updated_at' => '2022-01-28 10:56:09',
                'url' => '/products?category=5',
            ),
            18 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-10-20 04:20:31',
                'icon_class' => NULL,
                'id' => '19',
                'menu_id' => '4',
                'order' => '1',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Akun Saya',
                'updated_at' => '2022-01-28 10:52:25',
                'url' => '/profile',
            ),
            19 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-10-20 04:21:15',
                'icon_class' => NULL,
                'id' => '20',
                'menu_id' => '5',
                'order' => '24',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Kebijakan Privasi',
                'updated_at' => '2022-03-06 12:11:57',
                'url' => '/kebijakanprivasi',
            ),
            20 => 
            array (
                'color' => NULL,
                'created_at' => '2021-10-30 06:23:31',
                'icon_class' => 'voyager-people',
                'id' => '21',
                'menu_id' => '1',
                'order' => '25',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.customers.index',
                'target' => '_self',
                'title' => 'Customers',
                'updated_at' => '2021-10-30 06:23:31',
                'url' => '',
            ),
            21 => 
            array (
                'color' => NULL,
                'created_at' => '2021-11-06 13:26:40',
                'icon_class' => 'fa fa-globe',
                'id' => '22',
                'menu_id' => '1',
                'order' => '26',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.countries.index',
                'target' => '_self',
                'title' => 'Countries',
                'updated_at' => '2021-11-06 13:26:40',
                'url' => '',
            ),
            22 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-11-06 13:29:43',
                'icon_class' => 'fa fa-location-arrow',
                'id' => '23',
                'menu_id' => '1',
                'order' => '27',
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.provinces.index',
                'target' => '_self',
                'title' => 'Provinces',
                'updated_at' => '2021-11-06 13:33:43',
                'url' => '',
            ),
            23 => 
            array (
                'color' => NULL,
                'created_at' => '2021-11-06 13:34:12',
                'icon_class' => 'fa fa-building',
                'id' => '24',
                'menu_id' => '1',
                'order' => '28',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.cities.index',
                'target' => '_self',
                'title' => 'Cities',
                'updated_at' => '2021-11-06 13:34:12',
                'url' => '',
            ),
            24 => 
            array (
                'color' => NULL,
                'created_at' => '2021-11-09 02:09:55',
                'icon_class' => 'fa fa-info',
                'id' => '25',
                'menu_id' => '1',
                'order' => '29',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.product-attributes.index',
                'target' => '_self',
                'title' => 'Product Attributes',
                'updated_at' => '2021-11-09 02:09:55',
                'url' => '',
            ),
            25 => 
            array (
                'color' => NULL,
                'created_at' => '2021-11-09 02:32:17',
                'icon_class' => 'voyager-info-circled',
                'id' => '26',
                'menu_id' => '1',
                'order' => '30',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.attributes.index',
                'target' => '_self',
                'title' => 'Attributes',
                'updated_at' => '2021-11-09 02:32:17',
                'url' => '',
            ),
            26 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-12-03 07:03:32',
                'icon_class' => 'fas fa-shopping-cart',
                'id' => '27',
                'menu_id' => '1',
                'order' => '31',
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.transactions.index',
                'target' => '_self',
                'title' => 'Transactions',
                'updated_at' => '2021-12-03 07:04:16',
                'url' => '',
            ),
            27 => 
            array (
                'color' => NULL,
                'created_at' => '2021-12-22 13:49:44',
                'icon_class' => 'voyager-lock',
                'id' => '28',
                'menu_id' => '1',
                'order' => '32',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.permissions.index',
                'target' => '_self',
                'title' => 'Permissions',
                'updated_at' => '2021-12-22 13:49:44',
                'url' => '',
            ),
            28 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-15 16:45:15',
                'icon_class' => NULL,
                'id' => '29',
                'menu_id' => '2',
                'order' => '33',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Produk Lainnya',
                'updated_at' => '2022-01-28 10:49:42',
                'url' => '/products?category=13',
            ),
            29 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-15 16:59:03',
                'icon_class' => NULL,
                'id' => '31',
                'menu_id' => '3',
                'order' => '3',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tiang Shower',
                'updated_at' => '2022-01-28 10:56:09',
                'url' => '/products?category=2',
            ),
            30 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-15 16:59:12',
                'icon_class' => NULL,
                'id' => '32',
                'menu_id' => '3',
                'order' => '5',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Produk Lainnya',
                'updated_at' => '2022-01-28 10:56:09',
                'url' => '/products?category=13',
            ),
            31 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-15 16:59:26',
                'icon_class' => NULL,
                'id' => '33',
                'menu_id' => '3',
                'order' => '4',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Aksesoris Helm',
                'updated_at' => '2022-01-28 10:56:09',
                'url' => '/products?category=14',
            ),
            32 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-28 11:01:04',
                'icon_class' => NULL,
                'id' => '34',
                'menu_id' => '5',
                'order' => '34',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Hubungi Kami',
                'updated_at' => '2022-01-28 11:01:35',
                'url' => '/contact_us',
            ),
            33 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-01-28 11:01:28',
                'icon_class' => NULL,
                'id' => '35',
                'menu_id' => '5',
                'order' => '35',
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tentang Kami',
                'updated_at' => '2022-01-28 11:01:28',
                'url' => '/about_us',
            ),
            34 => 
            array (
                'color' => NULL,
                'created_at' => '2022-01-31 17:24:18',
                'icon_class' => 'far fa-comments',
                'id' => '36',
                'menu_id' => '1',
                'order' => '36',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.website-feedback.index',
                'target' => '_self',
                'title' => 'Feedbacks',
                'updated_at' => '2022-01-31 17:24:18',
                'url' => '',
            ),
            35 => 
            array (
                'color' => NULL,
                'created_at' => '2022-01-31 17:27:53',
                'icon_class' => 'fas fa-images',
                'id' => '37',
                'menu_id' => '1',
                'order' => '37',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.sliders.index',
                'target' => '_self',
                'title' => 'Sliders',
                'updated_at' => '2022-01-31 17:27:53',
                'url' => '',
            ),
            36 => 
            array (
                'color' => NULL,
                'created_at' => '2022-01-31 17:34:24',
                'icon_class' => 'voyager-home',
                'id' => '38',
                'menu_id' => '1',
                'order' => '38',
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.homepage-contents.index',
                'target' => '_self',
                'title' => 'Homepage Contents',
                'updated_at' => '2022-01-31 17:34:24',
                'url' => '',
            ),
        ));
        
        
    }
}