<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'TX 496 SRSN',
                'name' => 'Kran bath ub mixer tx 496 srsn',
                'description' => '',
                'display_price' => 3300000.0,
                'price' => 3300000.0,
                'weight' => 2500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/tx_496_srsn.jpg","\\/products\\/\\/tx_496_srsn2.jpg"]',
                'category_id' => 1,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'TX 492 SRS',
                'name' => 'Shower tiang tx 492 srs',
                'description' => '',
                'display_price' => 4200000.0,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/tx_492_srs.jpg","\\/products\\/\\/tx_492_srs2.jpg"]',
                'category_id' => 2,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'TOTO TX 493 SRS',
                'name' => 'Shower tiang toto tx 493 srs',
                'description' => '',
                'display_price' => 4300000.0,
                'price' => 4300000.0,
                'weight' => 1000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/toto_tx_493_srs.jpg","\\/products\\/\\/toto_tx_493_srs2.jpg"]',
                'category_id' => 2,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'TOTO TX 474 SRSN',
                'name' => 'Kran shower toto tx 474 srsn',
                'description' => '',
                'display_price' => 1500000.0,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/toto_tx_474_srsn.jpg","\\/products\\/\\/toto_tx_474_srsn2.jpg"]',
                'category_id' => 3,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'TX 47 SRSN',
                'name' => 'Kran bath tub tx 47 srsn',
                'description' => '',
                'display_price' => 1820000.0,
                'price' => 1820000.0,
                'weight' => 2500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/tx_47_srsn.jpg","\\/products\\/\\/tx_47_srsn2.jpg"]',
                'category_id' => 1,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'TOTO 492 SRS',
                'name' => 'Shower tiang toto 492 srs',
                'description' => '',
                'display_price' => 4200000.0,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/toto_492_srs.jpg","\\/products\\/\\/toto_492_srs2.jpg"]',
                'category_id' => 2,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'TOTO TX 492 SUN',
                'name' => 'Shower tiang set toto tx 492 sun',
                'description' => '',
                'display_price' => 3300000.0,
                'price' => 3300000.0,
                'weight' => 2500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/toto_tx_492_sun.jpg","\\/products\\/\\/toto_tx_492_sun2.jpg"]',
                'category_id' => 2,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'BTS65',
                'name' => 'Dorma BTS65',
                'description' => '',
                'display_price' => 900000.0,
                'price' => 900000.0,
                'weight' => 8000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/BTS65.jpg"]',
                'category_id' => 4,
                'brand_id' => 2,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'E3201B',
                'name' => 'Kran wastafel elite E3201B',
                'description' => '',
                'display_price' => 250000.0,
                'price' => 250000.0,
                'weight' => 600.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3201B.jpg"]',
                'category_id' => 5,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'W1911',
                'name' => 'Stopkran wasser handle bintang',
                'description' => 'Stopkran single merk wasser handle / puteran bintang',
                'display_price' => 110000.0,
                'price' => 110000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/W1911.jpg"]',
                'category_id' => 6,
                'brand_id' => 4,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'code' => NULL,
                'name' => 'Kran wastafel wasser putaran baling',
                'description' => 'Kran wastafel, kran tempat cuci tangan, merk wasser , model handle baling-baling',
                'display_price' => 225000.0,
                'price' => 225000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/wasser_putaran_baling.jpg","\\/products\\/\\/wasser_putaran_baling2.jpg"]',
                'category_id' => 7,
                'brand_id' => 4,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'SK SUS 304',
                'name' => 'Stop kran Cabang sus 304',
                'description' => 'Stopkran cabang, stopkran untuk closet + jetshower, tulisan on/off dibagian handle memudahkan dalam penggunaan, material sus 304 tidak mudah berkarat',
                'display_price' => 40000.0,
                'price' => 40000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/sus_304.jpg","\\/products\\/\\/sus_3042.jpg"]',
                'category_id' => 5,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'code' => NULL,
                'name' => 'Kran wastafel wasser',
                'description' => 'Kran wastafel , kran tempat cuci tangan merk wasser, handle model engkol',
                'display_price' => 210000.0,
                'price' => 210000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Kran_wastafel_wasser.jpg"]',
                'category_id' => 8,
                'brand_id' => 4,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'KKM SUS 304',
                'name' => 'Kran tembok SUS 304',
                'description' => 'Kran kamar mandi , kran tembok bahan stainless SUS 304 , awet tidak mudah berkarat',
                'display_price' => 55000.0,
                'price' => 55000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Kran_SUS_304.jpg"]',
                'category_id' => 3,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'code' => NULL,
                'name' => 'Floor Drain Stainless merk Executive',
                'description' => 'Floor Drain / Saringan Got Kamar mandi , bahan stainless finishing chrome',
                'display_price' => 75000.0,
                'price' => 75000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Floor_Drain_Executive.jpg"]',
                'category_id' => 9,
                'brand_id' => 5,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'KC SUS 304',
                'name' => 'Kran Cabang SUS 304 merk Kedeng',
                'description' => 'Kran kamar mandi,kran cabang untuk shower + bak/ember , material Stainless SUS 304, tidak mudah berkarat',
                'display_price' => 110000.0,
                'price' => 110000.0,
                'weight' => 650.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Kran_Cabang_SUS_304.jpg"]',
                'category_id' => 5,
                'brand_id' => 6,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'code' => NULL,
            'name' => 'Grease Trap Penyaring Lemak (KHUSUS GOSEND/GRAB)',
                'description' => 'Link khusus pengiriman via Gosend/Grab, untuk jasa pengiriman lain tapi atc link ini, transaksi akan kami tolak karena jasa pengiriman via jne/wahana/jnt menghitung berat volume',
                'display_price' => 330000.0,
                'price' => 330000.0,
                'weight' => 7000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Grease_Trap_Penyaring_Lemak","\\/products\\/\\/Grease_Trap_Penyaring_Lemak2","\\/products\\/\\/Grease_Trap_Penyaring_Lemak3","\\/products\\/\\/Grease_Trap_Penyaring_Lemak4"]',
                'category_id' => 10,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'code' => NULL,
                'name' => 'Shower tiang set stainless',
                'description' => 'Tanpa kran , bahan wall shower dan hand shower stainless',
                'display_price' => 475000.0,
                'price' => 475000.0,
                'weight' => 6000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Shower_tiang_set_stainless"]',
                'category_id' => 2,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'code' => NULL,
                'name' => 'Grease strap stainles 304',
                'description' => '',
                'display_price' => 1500000.0,
                'price' => 1500000.0,
                'weight' => 10000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/G_S_stainles_304.jpg"]',
                'category_id' => 11,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'code' => NULL,
                'name' => 'Semprotan air kenmaster',
                'description' => 'Bahan luar karet , dalam kuningan',
                'display_price' => 35000.0,
                'price' => 35000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Semprotan_air_kenmaster"]',
                'category_id' => 11,
                'brand_id' => 7,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'code' => NULL,
                'name' => 'Semprotan air kuningan KENMASTER',
                'description' => 'Merk kenmaster bahan kuningan',
                'display_price' => 35000.0,
                'price' => 35000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Semprotan_air_kuningan_KENMASTER"]',
                'category_id' => 11,
                'brand_id' => 7,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'code' => NULL,
                'name' => 'Safety valve water heater',
                'description' => 'Bisa untuk semua water heater , bahan kuningan',
                'display_price' => 70000.0,
                'price' => 70000.0,
                'weight' => 450.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Safety_valve_wh.jpg"]',
                'category_id' => 12,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'code' => NULL,
                'name' => 'Gembok cisa 60 ml',
                'description' => '',
                'display_price' => 475000.0,
                'price' => 475000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Gmbk_cisa_60ml.jpg"]',
                'category_id' => 13,
                'brand_id' => 8,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'code' => NULL,
                'name' => 'Gembok kend 50 ml',
                'description' => '',
                'display_price' => 190000.0,
                'price' => 190000.0,
                'weight' => 450.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Gmbk_kend_50ml.jpg"]',
                'category_id' => 13,
                'brand_id' => 9,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'code' => NULL,
                'name' => 'Gembok cisa 50ml',
                'description' => '',
                'display_price' => 400000.0,
                'price' => 400000.0,
                'weight' => 350.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Gmbk_cisa_50ml.jpg"]',
                'category_id' => 13,
                'brand_id' => 8,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'code' => NULL,
                'name' => 'Gembok cisa 60mm',
                'description' => '',
                'display_price' => 500000.0,
                'price' => 500000.0,
                'weight' => 300.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Gmbk _cisa_60mm.jpg"]',
                'category_id' => 13,
                'brand_id' => 8,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'code' => '150D',
                'name' => 'Gembok masterlock 150D',
                'description' => '',
                'display_price' => 240000.0,
                'price' => 240000.0,
                'weight' => 300.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/150D.jpg"]',
                'category_id' => 13,
                'brand_id' => 10,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'code' => '2960D',
                'name' => 'Gembok masterlock 2960 D',
                'description' => '',
                'display_price' => 375000.0,
                'price' => 375000.0,
                'weight' => 300.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/2960D.jpg"]',
                'category_id' => 13,
                'brand_id' => 10,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'AN 15 R',
                'name' => 'Ariston an 15 r',
                'description' => 'Pemanas air 15 liter , sudah termasuk bracket dan valve',
                'display_price' => 1750000.0,
                'price' => 1750000.0,
                'weight' => 7000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/an_15_r.jpg"]',
                'category_id' => 14,
                'brand_id' => 11,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'code' => NULL,
                'name' => 'Grease trap penyaring minyak',
                'description' => 'GREASE TRAP 
Bahan lebih bagus dari igt 30 

PENYARING LEMAK MINYAK KOTOR DARI PEMBUANGAN BAK DAPUR / SINK 

COCOK UTK RESTO, RMH TANGGA, APARTEMEN 

KEGUNAAN MENJAGA SALURAN PIPA TIDAK MAMPET 

UKURAN GREASE TRAP : 

PANJANG 42 CM 
LEBAR 32 CM 
TINGGI 28 CM 
Ukuran lubang 1 1/2” 
BAHAN PLASTIK 

WARNA ABU ABU',
                'display_price' => 330000.0,
                'price' => 330000.0,
                'weight' => 10000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/Grease_trap_penyaring_minyak.jpg","\\/products\\/\\/Grease_trap_penyaring_minyak2.jpg","\\/products\\/\\/Grease_trap_penyaring_minyak3.jpg","\\/products\\/\\/Grease_trap_penyaring_minyak4.jpg"]',
                'category_id' => 10,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'code' => NULL,
                'name' => 'set dual flush toto',
                'description' => 'Hanya alat doang tanpa pencetan closet
Merk gerberit toto
Barang cabutan dari closet ,',
                'display_price' => 195000.0,
                'price' => 195000.0,
                'weight' => 700.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/set_dual_flush_toto.jpg"]',
                'category_id' => 3,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'code' => NULL,
                'name' => 'cylinder knob coin solid',
                'description' => '',
                'display_price' => 85000.0,
                'price' => 85000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/cylinder_knob_coin_solid.jpg","\\/products\\/\\/cylinder_knob_coin_solid2.jpg"]',
                'category_id' => 11,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'G516/G660',
                'name' => 'SET DUAL FLUSH mekanik gerberit toto- type g516/g660',
                'description' => 'barang cabutan closet , bukan dalam dus',
                'display_price' => 390000.0,
                'price' => 390000.0,
                'weight' => 2000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/g516_g660.jpg","\\/products\\/\\/g516_g6602.jpg","\\/products\\/\\/g516_g6603.kpg"]',
                'category_id' => 3,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'code' => NULL,
                'name' => 'pt 10 dorma',
                'description' => '',
                'display_price' => 585000.0,
                'price' => 585000.0,
                'weight' => 2000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/pt10_dorma.jpg","\\/products\\/\\/pt10_dorma2.jpg","\\/products\\/\\/pt10_dorma3.jpg"]',
                'category_id' => 15,
                'brand_id' => 2,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'E 3212X',
                'name' => 'kran angsa tembok elite e 3212X',
                'description' => 'Garansi service 5 tahun
Bahan full kuningan
1/2"',
                'display_price' => 270000.0,
                'price' => 270000.0,
                'weight' => 1400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/e_3212X.jpg"]',
                'category_id' => 15,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'E 3205X',
                'name' => 'kran elite E 3205x',
                'description' => 'Garansi service 5 tahun kebocoran',
                'display_price' => 300000.0,
                'price' => 300000.0,
                'weight' => 1400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E_3205x.jpg"]',
                'category_id' => 15,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'GV-5988BST',
                'name' => 'kran panas dingin flexible meja',
                'description' => 'Garansi service 3 tahun
Merk giovani
Bahan kuningan',
                'display_price' => 775000.0,
                'price' => 775000.0,
                'weight' => 2400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/GV_5988BST.jpg"]',
                'category_id' => 15,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'FV-411',
                'name' => 'kran panas dingin flexible meja',
                'description' => 'Garansi service kebocoran 3 tahun',
                'display_price' => 450000.0,
                'price' => 450000.0,
                'weight' => 2000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/FV_411.jpg"]',
                'category_id' => 15,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'E3355',
                'name' => 'kran panas dingin meja elite E3355',
                'description' => 'Garansi 5 tahun kebocoran
Garansi service',
                'display_price' => 775000.0,
                'price' => 775000.0,
                'weight' => 3400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3355.jpg"]',
                'category_id' => 15,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'code' => NULL,
                'name' => 'kunci tambahan db2 solid',
                'description' => '',
                'display_price' => 125000.0,
                'price' => 125000.0,
                'weight' => 950.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/knci_tmbhn_db2_solid.jpg"]',
                'category_id' => 11,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'code' => NULL,
                'name' => 'kunci tambahan db1 solid',
                'description' => '',
                'display_price' => 100000.0,
                'price' => 100000.0,
                'weight' => 900.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/knci_tmbhn_db1_solid.jpg"]',
                'category_id' => 11,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'code' => NULL,
                'name' => 'kunci tambahan db0 solid',
                'description' => '',
                'display_price' => 75000.0,
                'price' => 75000.0,
                'weight' => 850.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/knci_tmbhn_db0_solid.jpg"]',
                'category_id' => 11,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'code' => NULL,
                'name' => 'silinder kunci komputer solid / double cylinder',
                'description' => '60 ml cylinder komputer solid',
                'display_price' => 90000.0,
                'price' => 90000.0,
                'weight' => 400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kunci_double_cylinder.jpg","\\/products\\/\\/kunci_double_cylinder2.jpg"]',
                'category_id' => 11,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'code' => NULL,
                'name' => 'kran cabang ina',
                'description' => 'Bahan kuningan ukuran 1/2"',
                'display_price' => 250000.0,
                'price' => 250000.0,
                'weight' => 1400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kran_cbg_ina.jpg"]',
                'category_id' => 3,
                'brand_id' => 13,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 'TS68 HO',
                'name' => 'door closer ts68 HO',
                'description' => 'With hold open',
                'display_price' => 600000.0,
                'price' => 600000.0,
                'weight' => 2000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/ts68_HO.jpg"]',
                'category_id' => 3,
                'brand_id' => 2,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 'CW421',
                'name' => 'closet toto cw421+ecowasser',
                'description' => 'Harga promo
Khusus gojek',
                'display_price' => 2200000.0,
                'price' => 2200000.0,
                'weight' => 6000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/cw421.jpg"]',
                'category_id' => 16,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 'CW421J',
                'name' => 'closet toto cw421j',
                'description' => 'Lubang as 50cm',
                'display_price' => 2100000.0,
                'price' => 2100000.0,
                'weight' => 7000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/cw421j.jpg"]',
                'category_id' => 16,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'code' => NULL,
                'name' => 'body pelor solid / badan kunci',
                'description' => 'Body pelor',
                'display_price' => 85000.0,
                'price' => 85000.0,
                'weight' => 1250.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/body_pelor_solid.jpg"]',
                'category_id' => 11,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 'HRE 61.41',
                'name' => 'handle solid HRE 61.41',
                'description' => '',
                'display_price' => 120000.0,
                'price' => 120000.0,
                'weight' => 1350.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/HRE_61.41.jpg"]',
                'category_id' => 11,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'code' => NULL,
                'name' => 'swing lockcase solid/body lidah solid/badan kunci',
                'description' => '40ml',
                'display_price' => 75000.0,
                'price' => 75000.0,
                'weight' => 1250.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/swing_lockcase_solid.jpg"]',
                'category_id' => 11,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'code' => NULL,
                'name' => 'kran bathup 1 set',
                'description' => '',
                'display_price' => 190000.0,
                'price' => 190000.0,
                'weight' => 2000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kran_bathup_1set.jpg"]',
                'category_id' => 3,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 'ART A290',
                'name' => 'floor drain injak stainless',
                'description' => '',
                'display_price' => 65000.0,
                'price' => 65000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/ART_A290.jpg"]',
                'category_id' => 9,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'code' => NULL,
                'name' => 'tombol closet dual flush',
                'description' => 'Tombol closet bisa besar bisa kecil',
                'display_price' => 60000.0,
                'price' => 60000.0,
                'weight' => 400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/tmbl_closet_dual_flush.jpg","\\/products\\/\\/tmbl_closet_dual_flush2.jpg"]',
                'category_id' => 16,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 'E2339',
                'name' => 'kran angsa meja flexibel kotak Elite E2339',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 550000.0,
                'price' => 550000.0,
                'weight' => 1750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E2339.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'code' => 'E2337',
                'name' => 'Kran angsa tembok flexibel kotak Elite E2337',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 565000.0,
                'price' => 565000.0,
                'weight' => 1750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E2337.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'code' => 'E2239',
                'name' => 'Kran angsa flexibel meja Elite E2239',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 550000.0,
                'price' => 550000.0,
                'weight' => 1650.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E2239.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'code' => 'E2237',
                'name' => 'Kran Angs Flexibel Tembok Elite E2237',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 560000.0,
                'price' => 560000.0,
                'weight' => 1650.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E2237.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'code' => 'E3213N',
                'name' => 'Kran Angsa Setengah Tegak Elite E3213N',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 240000.0,
                'price' => 240000.0,
                'weight' => 1350.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3213N.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'code' => 'E3211N',
                'name' => 'Kran bebek Elite E3211N',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 220000.0,
                'price' => 220000.0,
                'weight' => 1350.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3211N.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'code' => 'E4124',
                'name' => 'Stopkran Elite E4124',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 110000.0,
                'price' => 110000.0,
                'weight' => 850.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E4124.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'code' => 'E4123N',
                'name' => 'Stopkran Elite E4123N',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 91000.0,
                'price' => 91000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E4123N.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'code' => 'E4127',
                'name' => 'Stopkran Elite E4127',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 108000.0,
                'price' => 108000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E4127.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'code' => 'E3208K',
                'name' => 'Stopkran Tanam Elite E3208K',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 215000.0,
                'price' => 215000.0,
                'weight' => 1050.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3208K.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'code' => 'E3208N',
                'name' => 'Stopkran tanam Elite E3208N',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 186000.0,
                'price' => 186000.0,
                'weight' => 1050.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3208N.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'code' => 'E3207N',
                'name' => 'Stopkran Elite E3207N',
                'description' => 'miKran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 130000.0,
                'price' => 130000.0,
                'weight' => 800.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3207N.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'code' => 'E3201N',
                'name' => 'kran wastafel Elite E3201N',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 250000.0,
                'price' => 250000.0,
                'weight' => 1500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3201N.jpg"]',
                'category_id' => 7,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'code' => 'E3205N',
                'name' => 'Kran angsa meja Elite E3205N',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'display_price' => 290000.0,
                'price' => 290000.0,
                'weight' => 1950.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3205N.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'code' => 'E3204N',
                'name' => 'Kran cabang Elite E3204N',
                'description' => '',
                'display_price' => 270000.0,
                'price' => 270000.0,
                'weight' => 1650.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3204N.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'code' => 'E3203N',
                'name' => 'Kran taman Elite E3203N Bergaransi',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun. Beda kran tembok dengan kran taman ada pada moncong krannya, utk kran taman bisa dipakai untuk masuk selang.',
                'display_price' => 170000.0,
                'price' => 170000.0,
                'weight' => 375.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3203N.jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'code' => 'E3202N',
                'name' => 'Kran tembok Elite E3202N Bergaransi',
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun. Beda kran tembok dengan kran taman ada pada moncong krannya, utk kran taman bisa dipakai untuk masuk selang.',
                'display_price' => 145000.0,
                'price' => 145000.0,
                'weight' => 1200.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/E3202N .jpg"]',
                'category_id' => 3,
                'brand_id' => 3,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'code' => 'PT10',
                'name' => 'Patch Fitting Solid PT10',
                'description' => '',
                'display_price' => 130000.0,
                'price' => 130000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/PT10.jpg"]',
                'category_id' => 13,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'code' => 'PT21',
                'name' => 'Patch Fitting Solid PT21',
                'description' => 'pin untuk pintu kaca',
                'display_price' => 23000.0,
                'price' => 23000.0,
                'weight' => 300.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/PT21 .jpg","\\/products\\/\\/PT21_2 .jpg"]',
                'category_id' => 13,
                'brand_id' => 12,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'code' => 'CL110',
                'name' => 'kran tembok cello cl110',
                'description' => 'bahan kuningan bergaransi',
                'display_price' => 110000.0,
                'price' => 110000.0,
                'weight' => 550.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/cl110.jpg"]',
                'category_id' => 3,
                'brand_id' => 14,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'code' => NULL,
                'name' => 'kran tembok fio',
                'description' => '',
                'display_price' => 39500.0,
                'price' => 39500.0,
                'weight' => 250.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kran_tembok_fio.jpg"]',
                'category_id' => 3,
                'brand_id' => 15,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'code' => NULL,
                'name' => 'kran panas dingin 1 set',
                'description' => '',
                'display_price' => 250000.0,
                'price' => 250000.0,
                'weight' => 1000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kran_panas_dingin_1_set.png"]',
                'category_id' => 3,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'code' => NULL,
                'name' => 'double neple',
                'description' => 'Untuk water heater menggunakan 4 bh ukuran 1/2"',
                'display_price' => 25000.0,
                'price' => 25000.0,
                'weight' => 450.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/double_neple.png"]',
                'category_id' => 3,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'code' => NULL,
                'name' => 'selang bak cuci piring 1M',
                'description' => 'Bahan lumayan tebal',
                'display_price' => 27500.0,
                'price' => 27500.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/selang_bak_cuci_piring_1M.png"]',
                'category_id' => 17,
                'brand_id' => 7,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'code' => NULL,
                'name' => 'grandel tanam dekson 8"',
                'description' => 'Untuk pintu double bagian bawah',
                'display_price' => 75000.0,
                'price' => 75000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/grandel_tanam_dekson_8.png"]',
                'category_id' => 17,
                'brand_id' => 16,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'code' => NULL,
                'name' => 'afur stainless bcp',
                'description' => 'Untuk afur bcp bahan stainless',
                'display_price' => 40000.0,
                'price' => 40000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/afur_stainless_bcp.jpg","\\/products\\/\\/afur_stainless_bcp2.jpg","\\/products\\/\\/afur_stainless_bcp3.jpg"]',
                'category_id' => 17,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'code' => NULL,
                'name' => 'karet pembilas toto',
                'description' => '',
                'display_price' => 35000.0,
                'price' => 35000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kare_pembilas_toto.png"]',
                'category_id' => 17,
                'brand_id' => 1,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'code' => 'IGT-30',
                'name' => 'grease trap khusus gosend',
                'description' => 'UPDATE: stok sekarang IGT-30
Khusus gojek
UPDATE: stok sekarang IGT-30
Grease (Lemak) dari dapur adalah salah satu limbah domestik yang tidak bisa diurai secara alami.

Jika limbah grease ini tidak ditangani secara tepat, akan menyebabkan :
1. Saluran pipa akan tersumbat oleh grease (Lemak) yang membeku serta mengeras.
2. Jika sampai keluar ke saluran kota akan menyebabkan bau tidak sedap dan menimbulkan penyakit.
3. Jika sampai masuk kedalam septic tank akan mengganggu proses septic tank

Grease Trap Portable ini dipasang dibawah Sink dapur.

Keunggulan produk grease Trap ini:
1. Harga murah
2. Ramah lingkungan
3. Design dan bentuk yang membuat bau Lemak tidak keluar karena menggunakan teknologi Vacumm seperti pintu kulkas.

TYPE IGT-30
Dimensi (mm):
(P) 42,8x (L) 34 x (T) 35
Material :
Poly Propylene (PP Plastic)
Pipa & Fittings :
PVC Diameter 1 1 /2"
Basket :
Poly Propylene (PP Plastic)

Cara Kerja:
sekat 1 : Semua air cucian dari cucian di Sink, akan mengalir masuk kedalam Grease Trap Portable. Sampah padat bekas akan tersaring pada Basket Strainer diameter 2mm.
Sekat 2 : Setelah melalui basket, air + grease masuk, Grease akan naik ke permukaan air secara gravitasi karena berat jenis grease lebih ringan dari pada air.
Sekat 3 : Kemudian air yang berada dibawah grease akan keluar melalui pipa ke saluran kota. Sampah-sampah pada basket dan grease yang ada dipermukaan air harus dibersihkan secara berkala.

Pemasangan mudah dilakukan dan Instruksi Petunjuk Penggunaan Portable Grease Trap akan diberikan salam setiap kemasan.

kami memiliki desain standar pabrik, tanpa tambahan DRAIN yang dapat meminimalisir kebocoran. Sehingga dapat menghilangkan GARANSI pabrik.
',
                'display_price' => 330000.0,
                'price' => 330000.0,
                'weight' => 7000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/grease_trap_khusus_gosend.png","\\/products\\/\\/grease_trap_khusus_gosend2.png","\\/products\\/\\/grease_trap_khusus_gosend3.png"]',
                'category_id' => 17,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'code' => 'BTS 84',
                'name' => 'bts 84 dorma komplit',
                'description' => '1 set dengan stang , berat 7kg',
                'display_price' => 1475000.0,
                'price' => 1475000.0,
                'weight' => 7000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/bts_84.jpg","\\/products\\/\\/bts_842.jpg"]',
                'category_id' => 13,
                'brand_id' => 2,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'code' => NULL,
                'name' => 'pelampung radar',
                'description' => 'Spesifikasi:
Power Supply: 110/220V , 50/60Hz
Rated: 220V 7.5A / 110V 15A
Drat Konesi Switch: 3/4" x 14G / 1.0" x 12G
Drat Konesi Dudukan Switch: 3/4" x 14G
Batas Operasi Temperatur: 5 ~ 60 Celcius',
                'display_price' => 60000.0,
                'price' => 60000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/pelampung_radar.jpg","\\/products\\/\\/pelampung_radar2.jpg"]',
                'category_id' => 13,
                'brand_id' => 17,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'code' => 'MKN-035',
                'name' => 'kran sink waterplus mkn-035',
                'description' => 'bahan kuningan garansi 3 tahun',
                'display_price' => 1700000.0,
                'price' => 1700000.0,
                'weight' => 5000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/mkn_035.jpg","\\/products\\/\\n"]',
                'category_id' => 17,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'code' => NULL,
                'name' => 'lubangin sink',
                'description' => 'lubangin sink',
                'display_price' => 35000.0,
                'price' => 35000.0,
                'weight' => 250.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/lubangin_sink.jpg"]',
                'category_id' => 13,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'code' => NULL,
                'name' => 'keran kran angsa stainles / kran dapur',
                'description' => 'kran angsa stainles uk 1/2"',
                'display_price' => 185000.0,
                'price' => 185000.0,
                'weight' => 1250.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kran_angsa_stainles.jpg","\\/products\\/\\/kran_angsa_stainles2.jpg"]',
                'category_id' => 17,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'code' => NULL,
                'name' => 'DOOR CLOSER DEKSON 302 HOLD OPEN',
                'description' => 'Spesifikasi ; + Barang 100% , Original Dekson + Hold Open = Bisa Menahan Pintu Berhenti Sendiri Pada Sudut 90 Derajat + Tersedia Warna Silver + Beban Maks 60 kg',
                'display_price' => 235000.0,
                'price' => 235000.0,
                'weight' => 2000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/DOOR_CLOSER_DEKSON_302.jpg","\\/products\\/\\/DOOR_CLOSER_DEKSON_3022.jpg","\\/products\\/\\/DOOR_CLOSER_DEKSON_3023.jpg","\\/products\\/\\/DOOR_CLOSER_DEKSON_3024.jpg"]',
                'category_id' => 13,
                'brand_id' => 16,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'code' => NULL,
                'name' => 'selang bcp tarik',
                'description' => 'paling pendek 18cm ,panjang 87cm',
                'display_price' => 30000.0,
                'price' => 30000.0,
                'weight' => 600.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/selang_bcp_tarik.jpg","\\/products\\/\\/selang_bcp_tarik2.jpg"]',
                'category_id' => 13,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'code' => NULL,
                'name' => 'selang bak cuci piring 95cm',
                'description' => '',
                'display_price' => 75000.0,
                'price' => 75000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/selang_bak_cuci_piring_95cm.jpg"]',
                'category_id' => 13,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'code' => 'VNR 511',
                'name' => 'handle pintu 1 set vnr 511',
                'description' => 'handle tanggung vnr bahan cylinder kuningan',
                'display_price' => 77500.0,
                'price' => 77500.0,
                'weight' => 1400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/vnr_511.jpg","\\/products\\/\\/vnr_5112.jpg","\\/products\\/\\/vnr_5113.jpg","\\/products\\/\\/vnr_5114.jpg"]',
                'category_id' => 18,
                'brand_id' => 18,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'code' => NULL,
                'name' => 'bak cuci piring',
                'description' => 'KHUSUS GO SEND/ GO JEK bak cuci piring stainless pjg 75cmxlbr 40cm. kedaleman 12cm. sudah dilengkapi afur. Sebelum dikirim barang sudah dicek kondisinya, apabilabada cacat karena pengiriman kami tidak bertanggung jawab. Membeli = setuju',
                'display_price' => 130000.0,
                'price' => 130000.0,
                'weight' => 1000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/bak_cuci_piring.jpg"]',
                'category_id' => 17,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'code' => NULL,
                'name' => 'kran angsa flexible',
                'description' => 'ukuran 1/2" bahan campuran',
                'display_price' => 110000.0,
                'price' => 110000.0,
                'weight' => 700.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kran_angsa_flexible.jpg","\\/products\\/kran_angsa_flexible2.jpg"]',
                'category_id' => 19,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'code' => NULL,
                'name' => 'wall shower bagus , murah',
                'description' => 'wall shower bagus 3 fungsi , jika atc tambahkan buble warp untuk pengaman pengiriman',
                'display_price' => 70000.0,
                'price' => 70000.0,
                'weight' => 750.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/wall_shower_bagus.jpg","\\/products\\/\\/wall_shower_bagus2.jpg","\\/products\\/\\/wall_shower_bagus3.jpg"]',
                'category_id' => 13,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'code' => NULL,
                'name' => 'shower tiang + kran',
                'description' => 'showet tiang + kran cabang , pilih salah slah satu model kran ny , jika tidak d cantumkan di pemesanan ny akan saya kirim random',
                'display_price' => 450000.0,
                'price' => 450000.0,
                'weight' => 5000.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/shower_tiang_kran.jpg"]',
                'category_id' => 1,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'code' => NULL,
                'name' => 'kran panas dingin',
                'description' => '',
                'display_price' => 200000.0,
                'price' => 200000.0,
                'weight' => 500.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kran_panas_dingin.jpg"]',
                'category_id' => 3,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'code' => NULL,
                'name' => 'kran cabang murah',
                'description' => 'bahan babet ukuran 1/2"',
                'display_price' => 50000.0,
                'price' => 50000.0,
                'weight' => 400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/kran_cabang_murah.jpg","\\/products\\/\\/kran_cabang_murah2.jpg"]',
                'category_id' => 3,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'code' => NULL,
                'name' => 'hordeng kamar mandi',
                'description' => 'bahan katun , ukuran 180 X 180',
                'display_price' => 65000.0,
                'price' => 65000.0,
                'weight' => 250.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/hordeng_kamar_mandi.jpg"]',
                'category_id' => 13,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'code' => NULL,
                'name' => 'tiang hordeng',
                'description' => '90 x90 L',
                'display_price' => 65000.0,
                'price' => 65000.0,
                'weight' => 1400.0,
                'dimension_width' => 1.0,
                'dimension_height' => 1.0,
                'dimension_depth' => 1.0,
                'stock' => 0.0,
                'images' => '["\\/products\\/\\/tiang_hordeng.jpg"]',
                'category_id' => 20,
                'brand_id' => NULL,
                'created_at' => '2022-01-21 10:05:02',
                'updated_at' => '2022-01-21 10:05:02',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}