<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'brand_id' => NULL,
                'category_id' => '1',
                'code' => 'TX 496 SRSN',
                'created_at' => '2022-01-21 13:31:30',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '3300000',
                'id' => '1',
                'images' => '["/products//tx_496_srsn.jpg", "/products//tx_496_srsn2.jpg"]',
                'name' => 'Kran bath ub mixer tx 496 srsn',
                'price' => '3300000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:30',
                'weight' => '2500',
            ),
            1 => 
            array (
                'brand_id' => NULL,
                'category_id' => '2',
                'code' => 'TX 492 SRS',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '4200000',
                'id' => '2',
                'images' => '["/products//tx_492_srs.jpg", "/products//tx_492_srs2.jpg"]',
                'name' => 'Shower tiang tx 492 srs',
                'price' => '4200000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2500',
            ),
            2 => 
            array (
                'brand_id' => '1',
                'category_id' => '2',
                'code' => 'TOTO TX 493 SRS',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '4300000',
                'id' => '3',
                'images' => '["/products//toto_tx_493_srs.jpg", "/products//toto_tx_493_srs2.jpg"]',
                'name' => 'Shower tiang toto tx 493 srs',
                'price' => '4300000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1000',
            ),
            3 => 
            array (
                'brand_id' => '1',
                'category_id' => '3',
                'code' => 'TOTO TX 474 SRSN',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '1500000',
                'id' => '4',
                'images' => '["/products//toto_tx_474_srsn.jpg", "/products//toto_tx_474_srsn2.jpg"]',
                'name' => 'Kran shower toto tx 474 srsn',
                'price' => '1500000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2000',
            ),
            4 => 
            array (
                'brand_id' => NULL,
                'category_id' => '1',
                'code' => 'TX 47 SRSN',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '1820000',
                'id' => '5',
                'images' => '["/products//tx_47_srsn.jpg", "/products//tx_47_srsn2.jpg"]',
                'name' => 'Kran bath tub tx 47 srsn',
                'price' => '1820000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2500',
            ),
            5 => 
            array (
                'brand_id' => '1',
                'category_id' => '2',
                'code' => 'TOTO 492 SRS',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '4200000',
                'id' => '6',
                'images' => '["/products//toto_492_srs.jpg", "/products//toto_492_srs2.jpg"]',
                'name' => 'Shower tiang toto 492 srs',
                'price' => '4200000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2500',
            ),
            6 => 
            array (
                'brand_id' => '1',
                'category_id' => '2',
                'code' => 'TOTO TX 492 SUN',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '3300000',
                'id' => '7',
                'images' => '["/products//toto_tx_492_sun.jpg", "/products//toto_tx_492_sun2.jpg"]',
                'name' => 'Shower tiang set toto tx 492 sun',
                'price' => '3300000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2500',
            ),
            7 => 
            array (
                'brand_id' => '2',
                'category_id' => '4',
                'code' => 'BTS65',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '900000',
                'id' => '8',
                'images' => '["/products//BTS65.jpg"]',
                'name' => 'Dorma BTS65',
                'price' => '900000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '8000',
            ),
            8 => 
            array (
                'brand_id' => '3',
                'category_id' => '5',
                'code' => 'E3201B',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '250000',
                'id' => '9',
                'images' => '["/products//E3201B.jpg"]',
                'name' => 'Kran wastafel elite E3201B',
                'price' => '250000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '600',
            ),
            9 => 
            array (
                'brand_id' => '4',
                'category_id' => '6',
                'code' => 'W1911',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Stopkran single merk wasser handle / puteran bintang',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '110000',
                'id' => '10',
                'images' => '["/products//W1911.jpg"]',
                'name' => 'Stopkran wasser handle bintang',
                'price' => '110000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            10 => 
            array (
                'brand_id' => '4',
                'category_id' => '7',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran wastafel, kran tempat cuci tangan, merk wasser , model handle baling-baling',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '225000',
                'id' => '11',
                'images' => '["/products//wasser_putaran_baling.jpg", "/products//wasser_putaran_baling2.jpg"]',
                'name' => 'Kran wastafel wasser putaran baling',
                'price' => '225000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            11 => 
            array (
                'brand_id' => NULL,
                'category_id' => '5',
                'code' => 'SK SUS 304',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Stopkran cabang, stopkran untuk closet + jetshower, tulisan on/off dibagian handle memudahkan dalam penggunaan, material sus 304 tidak mudah berkarat',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '40000',
                'id' => '12',
                'images' => '["/products//sus_304.jpg", "/products//sus_3042.jpg"]',
                'name' => 'Stop kran Cabang sus 304',
                'price' => '40000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            12 => 
            array (
                'brand_id' => '4',
                'category_id' => '8',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran wastafel , kran tempat cuci tangan merk wasser, handle model engkol',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '210000',
                'id' => '13',
                'images' => '["/products//Kran_wastafel_wasser.jpg"]',
                'name' => 'Kran wastafel wasser',
                'price' => '210000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            13 => 
            array (
                'brand_id' => NULL,
                'category_id' => '3',
                'code' => 'KKM SUS 304',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran kamar mandi , kran tembok bahan stainless SUS 304 , awet tidak mudah berkarat',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '55000',
                'id' => '14',
                'images' => '["/products//Kran_SUS_304.jpg"]',
                'name' => 'Kran tembok SUS 304',
                'price' => '55000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            14 => 
            array (
                'brand_id' => '5',
                'category_id' => '9',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Floor Drain / Saringan Got Kamar mandi , bahan stainless finishing chrome',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '75000',
                'id' => '15',
                'images' => '["/products//Floor_Drain_Executive.jpg"]',
                'name' => 'Floor Drain Stainless merk Executive',
                'price' => '75000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            15 => 
            array (
                'brand_id' => '6',
                'category_id' => '5',
                'code' => 'KC SUS 304',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran kamar mandi,kran cabang untuk shower + bak/ember , material Stainless SUS 304, tidak mudah berkarat',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '110000',
                'id' => '16',
                'images' => '["/products//Kran_Cabang_SUS_304.jpg"]',
                'name' => 'Kran Cabang SUS 304 merk Kedeng',
                'price' => '110000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '650',
            ),
            16 => 
            array (
                'brand_id' => NULL,
                'category_id' => '10',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Link khusus pengiriman via Gosend/Grab, untuk jasa pengiriman lain tapi atc link ini, transaksi akan kami tolak karena jasa pengiriman via jne/wahana/jnt menghitung berat volume',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '330000',
                'id' => '17',
                'images' => '["/products//Grease_Trap_Penyaring_Lemak.jpg", "/products//Grease_Trap_Penyaring_Lemak2", "/products//Grease_Trap_Penyaring_Lemak3", "/products//Grease_Trap_Penyaring_Lemak4"]',
            'name' => 'Grease Trap Penyaring Lemak (KHUSUS GOSEND/GRAB)',
                'price' => '330000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '7000',
            ),
            17 => 
            array (
                'brand_id' => NULL,
                'category_id' => '2',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Tanpa kran , bahan wall shower dan hand shower stainless',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '475000',
                'id' => '18',
                'images' => '["/products//Shower_tiang_set_stainless.jpg"]',
                'name' => 'Shower tiang set stainless',
                'price' => '475000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '6000',
            ),
            18 => 
            array (
                'brand_id' => NULL,
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '1500000',
                'id' => '19',
                'images' => '["/products//G_S_stainles_304.jpg"]',
                'name' => 'Grease strap stainles 304',
                'price' => '1500000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '10000',
            ),
            19 => 
            array (
                'brand_id' => '7',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Bahan luar karet , dalam kuningan',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '35000',
                'id' => '20',
                'images' => '["/products//Semprotan_air_kenmaster.jpg"]',
                'name' => 'Semprotan air kenmaster',
                'price' => '35000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            20 => 
            array (
                'brand_id' => '7',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Merk kenmaster bahan kuningan',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '35000',
                'id' => '21',
                'images' => '["/products//Semprotan_air_kuningan_KENMASTER.jpg"]',
                'name' => 'Semprotan air kuningan KENMASTER',
                'price' => '35000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            21 => 
            array (
                'brand_id' => NULL,
                'category_id' => '12',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Bisa untuk semua water heater , bahan kuningan',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '70000',
                'id' => '22',
                'images' => '["/products//Safety_valve_wh.jpg"]',
                'name' => 'Safety valve water heater',
                'price' => '70000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '450',
            ),
            22 => 
            array (
                'brand_id' => '8',
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '475000',
                'id' => '23',
                'images' => '["/products//Gmbk_cisa_60ml.jpg"]',
                'name' => 'Gembok cisa 60 ml',
                'price' => '475000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            23 => 
            array (
                'brand_id' => '9',
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '190000',
                'id' => '24',
                'images' => '["/products//Gmbk_kend_50ml.jpg"]',
                'name' => 'Gembok kend 50 ml',
                'price' => '190000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '450',
            ),
            24 => 
            array (
                'brand_id' => '8',
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '400000',
                'id' => '25',
                'images' => '["/products//Gmbk_cisa_50ml.jpg"]',
                'name' => 'Gembok cisa 50ml',
                'price' => '400000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '350',
            ),
            25 => 
            array (
                'brand_id' => '8',
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Gembok cisa 60mm',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '500000',
                'id' => '26',
                'images' => '["products/Gmbk_cisa_60ml.jpg"]',
                'name' => 'Gembok cisa 60mm',
                'price' => '500000',
                'stock' => '0',
                'updated_at' => '2022-01-28 10:42:33',
                'weight' => '300',
            ),
            26 => 
            array (
                'brand_id' => '10',
                'category_id' => '13',
                'code' => '150D',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '240000',
                'id' => '27',
                'images' => '["/products//150D.jpg"]',
                'name' => 'Gembok masterlock 150D',
                'price' => '240000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '300',
            ),
            27 => 
            array (
                'brand_id' => '10',
                'category_id' => '13',
                'code' => '2960D',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '375000',
                'id' => '28',
                'images' => '["/products//2960D.jpg"]',
                'name' => 'Gembok masterlock 2960 D',
                'price' => '375000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '300',
            ),
            28 => 
            array (
                'brand_id' => '11',
                'category_id' => '14',
                'code' => 'AN 15 R',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Pemanas air 15 liter , sudah termasuk bracket dan valve',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '1750000',
                'id' => '29',
                'images' => '["/products//an_15_r.jpg"]',
                'name' => 'Ariston an 15 r',
                'price' => '1750000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '7000',
            ),
            29 => 
            array (
                'brand_id' => NULL,
                'category_id' => '10',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'GREASE TRAP 
Bahan lebih bagus dari igt 30 

PENYARING LEMAK MINYAK KOTOR DARI PEMBUANGAN BAK DAPUR / SINK 

COCOK UTK RESTO, RMH TANGGA, APARTEMEN 

KEGUNAAN MENJAGA SALURAN PIPA TIDAK MAMPET 

UKURAN GREASE TRAP : 

PANJANG 42 CM 
LEBAR 32 CM 
TINGGI 28 CM 
Ukuran lubang 1 1/2” 
BAHAN PLASTIK 

WARNA ABU ABU',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '330000',
                'id' => '30',
                'images' => '["/products//Grease_trap_penyaring_minyak.jpg", "/products//Grease_trap_penyaring_minyak2.jpg", "/products//Grease_trap_penyaring_minyak3.jpg", "/products//Grease_trap_penyaring_minyak4.jpg"]',
                'name' => 'Grease trap penyaring minyak',
                'price' => '330000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '10000',
            ),
            30 => 
            array (
                'brand_id' => '1',
                'category_id' => '3',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Hanya alat doang tanpa pencetan closet
Merk gerberit toto
Barang cabutan dari closet ,',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '195000',
                'id' => '31',
                'images' => '["/products//set_dual_flush_toto.jpg"]',
                'name' => 'set dual flush toto',
                'price' => '195000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '700',
            ),
            31 => 
            array (
                'brand_id' => '12',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '85000',
                'id' => '32',
                'images' => '["/products//cylinder_knob_coin_solid.jpg", "/products//cylinder_knob_coin_solid2.jpg"]',
                'name' => 'cylinder knob coin solid',
                'price' => '85000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            32 => 
            array (
                'brand_id' => '1',
                'category_id' => '3',
                'code' => 'G516/G660',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'barang cabutan closet , bukan dalam dus',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '390000',
                'id' => '33',
                'images' => '["/products//g516_g660.jpg", "/products//g516_g6602.jpg", "/products//g516_g6603.kpg"]',
                'name' => 'SET DUAL FLUSH mekanik gerberit toto- type g516/g660',
                'price' => '390000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2000',
            ),
            33 => 
            array (
                'brand_id' => '2',
                'category_id' => '15',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '585000',
                'id' => '34',
                'images' => '["/products//pt10_dorma.jpg", "/products//pt10_dorma2.jpg", "/products//pt10_dorma3.jpg"]',
                'name' => 'pt 10 dorma',
                'price' => '585000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2000',
            ),
            34 => 
            array (
                'brand_id' => '3',
                'category_id' => '15',
                'code' => 'E 3212X',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Garansi service 5 tahun
Bahan full kuningan
1/2"',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '270000',
                'id' => '35',
                'images' => '["/products//e_3212X.jpg"]',
                'name' => 'kran angsa tembok elite e 3212X',
                'price' => '270000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1400',
            ),
            35 => 
            array (
                'brand_id' => '3',
                'category_id' => '15',
                'code' => 'E 3205X',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Garansi service 5 tahun kebocoran',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '300000',
                'id' => '36',
                'images' => '["/products//E_3205x.jpg"]',
                'name' => 'kran elite E 3205x',
                'price' => '300000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1400',
            ),
            36 => 
            array (
                'brand_id' => NULL,
                'category_id' => '15',
                'code' => 'GV-5988BST',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Garansi service 3 tahun
Merk giovani
Bahan kuningan',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '775000',
                'id' => '37',
                'images' => '["/products//GV_5988BST.jpg"]',
                'name' => 'kran panas dingin flexible meja',
                'price' => '775000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2400',
            ),
            37 => 
            array (
                'brand_id' => NULL,
                'category_id' => '15',
                'code' => 'FV-411',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Garansi service kebocoran 3 tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '450000',
                'id' => '38',
                'images' => '["/products//FV_411.jpg"]',
                'name' => 'kran panas dingin flexible meja',
                'price' => '450000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2000',
            ),
            38 => 
            array (
                'brand_id' => '3',
                'category_id' => '15',
                'code' => 'E3355',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Garansi 5 tahun kebocoran
Garansi service',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '775000',
                'id' => '39',
                'images' => '["/products//E3355.jpg"]',
                'name' => 'kran panas dingin meja elite E3355',
                'price' => '775000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '3400',
            ),
            39 => 
            array (
                'brand_id' => '12',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '125000',
                'id' => '40',
                'images' => '["/products//knci_tmbhn_db2_solid.jpg"]',
                'name' => 'kunci tambahan db2 solid',
                'price' => '125000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '950',
            ),
            40 => 
            array (
                'brand_id' => '12',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '100000',
                'id' => '41',
                'images' => '["/products//knci_tmbhn_db1_solid.jpg"]',
                'name' => 'kunci tambahan db1 solid',
                'price' => '100000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '900',
            ),
            41 => 
            array (
                'brand_id' => '12',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '75000',
                'id' => '42',
                'images' => '["/products//knci_tmbhn_db0_solid.jpg"]',
                'name' => 'kunci tambahan db0 solid',
                'price' => '75000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '850',
            ),
            42 => 
            array (
                'brand_id' => '12',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '60 ml cylinder komputer solid',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '90000',
                'id' => '43',
                'images' => '["/products//kunci_double_cylinder.jpg", "/products//kunci_double_cylinder2.jpg"]',
                'name' => 'silinder kunci komputer solid / double cylinder',
                'price' => '90000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '400',
            ),
            43 => 
            array (
                'brand_id' => '13',
                'category_id' => '3',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Bahan kuningan ukuran 1/2"',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '250000',
                'id' => '44',
                'images' => '["/products//kran_cbg_ina.jpg"]',
                'name' => 'kran cabang ina',
                'price' => '250000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1400',
            ),
            44 => 
            array (
                'brand_id' => '2',
                'category_id' => '3',
                'code' => 'TS68 HO',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'With hold open',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '600000',
                'id' => '45',
                'images' => '["/products//ts68_HO.jpg"]',
                'name' => 'door closer ts68 HO',
                'price' => '600000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2000',
            ),
            45 => 
            array (
                'brand_id' => '1',
                'category_id' => '16',
                'code' => 'CW421',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Harga promo
Khusus gojek',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '2200000',
                'id' => '46',
                'images' => '["/products//cw421.jpg"]',
                'name' => 'closet toto cw421+ecowasser',
                'price' => '2200000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '6000',
            ),
            46 => 
            array (
                'brand_id' => '1',
                'category_id' => '16',
                'code' => 'CW421J',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Lubang as 50cm',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '2100000',
                'id' => '47',
                'images' => '["/products//cw421j.jpg"]',
                'name' => 'closet toto cw421j',
                'price' => '2100000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '7000',
            ),
            47 => 
            array (
                'brand_id' => '12',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Body pelor',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '85000',
                'id' => '48',
                'images' => '["/products//body_pelor_solid.jpg"]',
                'name' => 'body pelor solid / badan kunci',
                'price' => '85000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1250',
            ),
            48 => 
            array (
                'brand_id' => '12',
                'category_id' => '11',
                'code' => 'HRE 61.41',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '120000',
                'id' => '49',
                'images' => '["/products//HRE_61.41.jpg"]',
                'name' => 'handle solid HRE 61.41',
                'price' => '120000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1350',
            ),
            49 => 
            array (
                'brand_id' => '12',
                'category_id' => '11',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '40ml',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '75000',
                'id' => '50',
                'images' => '["/products//swing_lockcase_solid.jpg"]',
                'name' => 'swing lockcase solid/body lidah solid/badan kunci',
                'price' => '75000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1250',
            ),
            50 => 
            array (
                'brand_id' => NULL,
                'category_id' => '3',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '190000',
                'id' => '51',
                'images' => '["/products//kran_bathup_1set.jpg"]',
                'name' => 'kran bathup 1 set',
                'price' => '190000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2000',
            ),
            51 => 
            array (
                'brand_id' => NULL,
                'category_id' => '9',
                'code' => 'ART A290',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '65000',
                'id' => '52',
                'images' => '["/products//ART_A290.jpg"]',
                'name' => 'floor drain injak stainless',
                'price' => '65000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            52 => 
            array (
                'brand_id' => NULL,
                'category_id' => '16',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Tombol closet bisa besar bisa kecil',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '60000',
                'id' => '53',
                'images' => '["/products//tmbl_closet_dual_flush.jpg", "/products//tmbl_closet_dual_flush2.jpg"]',
                'name' => 'tombol closet dual flush',
                'price' => '60000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '400',
            ),
            53 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E2339',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '550000',
                'id' => '54',
                'images' => '["/products//E2339.jpg"]',
                'name' => 'kran angsa meja flexibel kotak Elite E2339',
                'price' => '550000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1750',
            ),
            54 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E2337',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '565000',
                'id' => '55',
                'images' => '["/products//E2337.jpg"]',
                'name' => 'Kran angsa tembok flexibel kotak Elite E2337',
                'price' => '565000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1750',
            ),
            55 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E2239',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '550000',
                'id' => '56',
                'images' => '["/products//E2239.jpg"]',
                'name' => 'Kran angsa flexibel meja Elite E2239',
                'price' => '550000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1650',
            ),
            56 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E2237',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '560000',
                'id' => '57',
                'images' => '["/products//E2237.jpg"]',
                'name' => 'Kran Angs Flexibel Tembok Elite E2237',
                'price' => '560000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1650',
            ),
            57 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3213N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '240000',
                'id' => '58',
                'images' => '["/products//E3213N.jpg"]',
                'name' => 'Kran Angsa Setengah Tegak Elite E3213N',
                'price' => '240000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1350',
            ),
            58 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3211N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '220000',
                'id' => '59',
                'images' => '["/products//E3211N.jpg"]',
                'name' => 'Kran bebek Elite E3211N',
                'price' => '220000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1350',
            ),
            59 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E4124',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '110000',
                'id' => '60',
                'images' => '["/products//E4124.jpg"]',
                'name' => 'Stopkran Elite E4124',
                'price' => '110000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '850',
            ),
            60 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E4123N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '91000',
                'id' => '61',
                'images' => '["/products//E4123N.jpg"]',
                'name' => 'Stopkran Elite E4123N',
                'price' => '91000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            61 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E4127',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '108000',
                'id' => '62',
                'images' => '["/products//E4127.jpg"]',
                'name' => 'Stopkran Elite E4127',
                'price' => '108000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            62 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3208K',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '215000',
                'id' => '63',
                'images' => '["/products//E3208K.jpg"]',
                'name' => 'Stopkran Tanam Elite E3208K',
                'price' => '215000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1050',
            ),
            63 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3208N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '186000',
                'id' => '64',
                'images' => '["/products//E3208N.jpg"]',
                'name' => 'Stopkran tanam Elite E3208N',
                'price' => '186000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1050',
            ),
            64 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3207N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'miKran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '130000',
                'id' => '65',
                'images' => '["/products//E3207N.jpg"]',
                'name' => 'Stopkran Elite E3207N',
                'price' => '130000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '800',
            ),
            65 => 
            array (
                'brand_id' => '3',
                'category_id' => '7',
                'code' => 'E3201N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '250000',
                'id' => '66',
                'images' => '["/products//E3201N.jpg"]',
                'name' => 'kran wastafel Elite E3201N',
                'price' => '250000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1500',
            ),
            66 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3205N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '290000',
                'id' => '67',
                'images' => '["/products//E3205N.jpg"]',
                'name' => 'Kran angsa meja Elite E3205N',
                'price' => '290000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1950',
            ),
            67 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3204N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '270000',
                'id' => '68',
                'images' => '["/products//E3204N.jpg"]',
                'name' => 'Kran cabang Elite E3204N',
                'price' => '270000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1650',
            ),
            68 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3203N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun. Beda kran tembok dengan kran taman ada pada moncong krannya, utk kran taman bisa dipakai untuk masuk selang.',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '170000',
                'id' => '69',
                'images' => '["/products//E3203N.jpg"]',
                'name' => 'Kran taman Elite E3203N Bergaransi',
                'price' => '170000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '375',
            ),
            69 => 
            array (
                'brand_id' => '3',
                'category_id' => '3',
                'code' => 'E3202N',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Kran merk Elite berlisensi Itali, bahan kuningan tebal, garansi 3tahun. Beda kran tembok dengan kran taman ada pada moncong krannya, utk kran taman bisa dipakai untuk masuk selang.',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '145000',
                'id' => '70',
                'images' => '["/products//E3202N .jpg"]',
                'name' => 'Kran tembok Elite E3202N Bergaransi',
                'price' => '145000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1200',
            ),
            70 => 
            array (
                'brand_id' => '12',
                'category_id' => '13',
                'code' => 'PT10',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '130000',
                'id' => '71',
                'images' => '["/products//PT10.jpg"]',
                'name' => 'Patch Fitting Solid PT10',
                'price' => '130000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            71 => 
            array (
                'brand_id' => '12',
                'category_id' => '13',
                'code' => 'PT21',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'pin untuk pintu kaca',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '23000',
                'id' => '72',
                'images' => '["products/PT21.jpg", "products/PT21_2.jpg"]',
                'name' => 'Patch Fitting Solid PT21',
                'price' => '23000',
                'stock' => '0',
                'updated_at' => '2022-01-28 10:27:01',
                'weight' => '300',
            ),
            72 => 
            array (
                'brand_id' => '14',
                'category_id' => '3',
                'code' => 'CL110',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'bahan kuningan bergaransi',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '110000',
                'id' => '73',
                'images' => '["/products//cl110.jpg"]',
                'name' => 'kran tembok cello cl110',
                'price' => '110000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '550',
            ),
            73 => 
            array (
                'brand_id' => '15',
                'category_id' => '3',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '39500',
                'id' => '74',
                'images' => '["/products//kran_tembok_fio.jpg"]',
                'name' => 'kran tembok fio',
                'price' => '39500',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '250',
            ),
            74 => 
            array (
                'brand_id' => NULL,
                'category_id' => '3',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '250000',
                'id' => '75',
                'images' => '["/products//kran_panas_dingin_1_set.png"]',
                'name' => 'kran panas dingin 1 set',
                'price' => '250000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1000',
            ),
            75 => 
            array (
                'brand_id' => NULL,
                'category_id' => '3',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Untuk water heater menggunakan 4 bh ukuran 1/2"',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '25000',
                'id' => '76',
                'images' => '["/products//double_neple.png"]',
                'name' => 'double neple',
                'price' => '25000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '450',
            ),
            76 => 
            array (
                'brand_id' => '7',
                'category_id' => '17',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Bahan lumayan tebal',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '27500',
                'id' => '77',
                'images' => '["/products//selang_bak_cuci_piring_1M.png"]',
                'name' => 'selang bak cuci piring 1M',
                'price' => '27500',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            77 => 
            array (
                'brand_id' => '16',
                'category_id' => '17',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Untuk pintu double bagian bawah',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '75000',
                'id' => '78',
                'images' => '["/products//grandel_tanam_dekson_8.png"]',
                'name' => 'grandel tanam dekson 8"',
                'price' => '75000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            78 => 
            array (
                'brand_id' => NULL,
                'category_id' => '17',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Untuk afur bcp bahan stainless',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '40000',
                'id' => '79',
                'images' => '["/products//afur_stainless_bcp.jpg", "/products//afur_stainless_bcp2.jpg", "/products//afur_stainless_bcp3.jpg"]',
                'name' => 'afur stainless bcp',
                'price' => '40000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            79 => 
            array (
                'brand_id' => '1',
                'category_id' => '17',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'karet pembilas toto',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '35000',
                'id' => '80',
                'images' => '["products/karet_pembilas_toto.png"]',
                'name' => 'karet pembilas toto',
                'price' => '35000',
                'stock' => '0',
                'updated_at' => '2022-01-28 10:36:25',
                'weight' => '500',
            ),
            80 => 
            array (
                'brand_id' => NULL,
                'category_id' => '17',
                'code' => 'IGT-30',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'UPDATE: stok sekarang IGT-30
Khusus gojek
UPDATE: stok sekarang IGT-30
Grease (Lemak) dari dapur adalah salah satu limbah domestik yang tidak bisa diurai secara alami.

Jika limbah grease ini tidak ditangani secara tepat, akan menyebabkan :
1. Saluran pipa akan tersumbat oleh grease (Lemak) yang membeku serta mengeras.
2. Jika sampai keluar ke saluran kota akan menyebabkan bau tidak sedap dan menimbulkan penyakit.
3. Jika sampai masuk kedalam septic tank akan mengganggu proses septic tank

Grease Trap Portable ini dipasang dibawah Sink dapur.

Keunggulan produk grease Trap ini:
1. Harga murah
2. Ramah lingkungan
3. Design dan bentuk yang membuat bau Lemak tidak keluar karena menggunakan teknologi Vacumm seperti pintu kulkas.

TYPE IGT-30
Dimensi (mm):
(P) 42,8x (L) 34 x (T) 35
Material :
Poly Propylene (PP Plastic)
Pipa & Fittings :
PVC Diameter 1 1 /2"
Basket :
Poly Propylene (PP Plastic)

Cara Kerja:
sekat 1 : Semua air cucian dari cucian di Sink, akan mengalir masuk kedalam Grease Trap Portable. Sampah padat bekas akan tersaring pada Basket Strainer diameter 2mm.
Sekat 2 : Setelah melalui basket, air + grease masuk, Grease akan naik ke permukaan air secara gravitasi karena berat jenis grease lebih ringan dari pada air.
Sekat 3 : Kemudian air yang berada dibawah grease akan keluar melalui pipa ke saluran kota. Sampah-sampah pada basket dan grease yang ada dipermukaan air harus dibersihkan secara berkala.

Pemasangan mudah dilakukan dan Instruksi Petunjuk Penggunaan Portable Grease Trap akan diberikan salam setiap kemasan.

kami memiliki desain standar pabrik, tanpa tambahan DRAIN yang dapat meminimalisir kebocoran. Sehingga dapat menghilangkan GARANSI pabrik.
',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '330000',
                'id' => '81',
                'images' => '["/products//grease_trap_khusus_gosend.png", "/products//grease_trap_khusus_gosend2.png", "/products//grease_trap_khusus_gosend3.png"]',
                'name' => 'grease trap khusus gosend',
                'price' => '330000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '7000',
            ),
            81 => 
            array (
                'brand_id' => '2',
                'category_id' => '13',
                'code' => 'BTS 84',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '1 set dengan stang , berat 7kg',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '1475000',
                'id' => '82',
                'images' => '["/products//bts_84.jpg", "/products//bts_842.jpg"]',
                'name' => 'bts 84 dorma komplit',
                'price' => '1475000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '7000',
            ),
            82 => 
            array (
                'brand_id' => '17',
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Spesifikasi:
Power Supply: 110/220V , 50/60Hz
Rated: 220V 7.5A / 110V 15A
Drat Konesi Switch: 3/4" x 14G / 1.0" x 12G
Drat Konesi Dudukan Switch: 3/4" x 14G
Batas Operasi Temperatur: 5 ~ 60 Celcius',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '60000',
                'id' => '83',
                'images' => '["/products//pelampung_radar.jpg", "/products//pelampung_radar2.jpg"]',
                'name' => 'pelampung radar',
                'price' => '60000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            83 => 
            array (
                'brand_id' => NULL,
                'category_id' => '17',
                'code' => 'MKN-035',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'bahan kuningan garansi 3 tahun',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '1700000',
                'id' => '84',
                'images' => '["/products//mkn_035.jpg", "/products/\\n"]',
                'name' => 'kran sink waterplus mkn-035',
                'price' => '1700000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '5000',
            ),
            84 => 
            array (
                'brand_id' => NULL,
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'lubangin sink',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '35000',
                'id' => '85',
                'images' => '["/products//lubangin_sink.jpg"]',
                'name' => 'lubangin sink',
                'price' => '35000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '250',
            ),
            85 => 
            array (
                'brand_id' => NULL,
                'category_id' => '17',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'kran angsa stainles uk 1/2"',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '185000',
                'id' => '86',
                'images' => '["/products//kran_angsa_stainles.jpg", "/products//kran_angsa_stainles2.jpg"]',
                'name' => 'keran kran angsa stainles / kran dapur',
                'price' => '185000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1250',
            ),
            86 => 
            array (
                'brand_id' => '16',
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'Spesifikasi ; + Barang 100% , Original Dekson + Hold Open = Bisa Menahan Pintu Berhenti Sendiri Pada Sudut 90 Derajat + Tersedia Warna Silver + Beban Maks 60 kg',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '235000',
                'id' => '87',
                'images' => '["/products//DOOR_CLOSER_DEKSON_302.jpg", "/products//DOOR_CLOSER_DEKSON_3022.jpg", "/products//DOOR_CLOSER_DEKSON_3023.jpg", "/products//DOOR_CLOSER_DEKSON_3024.jpg"]',
                'name' => 'DOOR CLOSER DEKSON 302 HOLD OPEN',
                'price' => '235000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '2000',
            ),
            87 => 
            array (
                'brand_id' => NULL,
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'paling pendek 18cm ,panjang 87cm',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '30000',
                'id' => '88',
                'images' => '["/products//selang_bcp_tarik.jpg", "/products//selang_bcp_tarik2.jpg"]',
                'name' => 'selang bcp tarik',
                'price' => '30000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '600',
            ),
            88 => 
            array (
                'brand_id' => NULL,
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '75000',
                'id' => '89',
                'images' => '["/products//selang_bak_cuci_piring_95cm.jpg"]',
                'name' => 'selang bak cuci piring 95cm',
                'price' => '75000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            89 => 
            array (
                'brand_id' => '18',
                'category_id' => '18',
                'code' => 'VNR 511',
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'handle tanggung vnr bahan cylinder kuningan',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '77500',
                'id' => '90',
                'images' => '["/products//vnr_511.jpg", "/products//vnr_5112.jpg", "/products//vnr_5113.jpg", "/products//vnr_5114.jpg"]',
                'name' => 'handle pintu 1 set vnr 511',
                'price' => '77500',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1400',
            ),
            90 => 
            array (
                'brand_id' => NULL,
                'category_id' => '17',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'KHUSUS GO SEND/ GO JEK bak cuci piring stainless pjg 75cmxlbr 40cm. kedaleman 12cm. sudah dilengkapi afur. Sebelum dikirim barang sudah dicek kondisinya, apabilabada cacat karena pengiriman kami tidak bertanggung jawab. Membeli = setuju',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '130000',
                'id' => '91',
                'images' => '["/products//bak_cuci_piring.jpg"]',
                'name' => 'bak cuci piring',
                'price' => '130000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1000',
            ),
            91 => 
            array (
                'brand_id' => NULL,
                'category_id' => '19',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'ukuran 1/2" bahan campuran',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '110000',
                'id' => '92',
                'images' => '["/products//kran_angsa_flexible.jpg", "/products/kran_angsa_flexible2.jpg"]',
                'name' => 'kran angsa flexible',
                'price' => '110000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '700',
            ),
            92 => 
            array (
                'brand_id' => NULL,
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'wall shower bagus 3 fungsi , jika atc tambahkan buble warp untuk pengaman pengiriman',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '70000',
                'id' => '93',
                'images' => '["/products//wall_shower_bagus.jpg", "/products//wall_shower_bagus2.jpg", "/products//wall_shower_bagus3.jpg"]',
                'name' => 'wall shower bagus , murah',
                'price' => '70000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '750',
            ),
            93 => 
            array (
                'brand_id' => NULL,
                'category_id' => '1',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'showet tiang + kran cabang , pilih salah slah satu model kran ny , jika tidak d cantumkan di pemesanan ny akan saya kirim random',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '450000',
                'id' => '94',
                'images' => '["/products//shower_tiang_kran.jpg"]',
                'name' => 'shower tiang + kran',
                'price' => '450000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '5000',
            ),
            94 => 
            array (
                'brand_id' => NULL,
                'category_id' => '3',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '200000',
                'id' => '95',
                'images' => '["/products//kran_panas_dingin.jpg"]',
                'name' => 'kran panas dingin',
                'price' => '200000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '500',
            ),
            95 => 
            array (
                'brand_id' => NULL,
                'category_id' => '3',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'bahan babet ukuran 1/2"',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '50000',
                'id' => '96',
                'images' => '["/products//kran_cabang_murah.jpg", "/products//kran_cabang_murah2.jpg"]',
                'name' => 'kran cabang murah',
                'price' => '50000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '400',
            ),
            96 => 
            array (
                'brand_id' => NULL,
                'category_id' => '13',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => 'bahan katun , ukuran 180 X 180',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '65000',
                'id' => '97',
                'images' => '["/products//hordeng_kamar_mandi.jpg"]',
                'name' => 'hordeng kamar mandi',
                'price' => '65000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '250',
            ),
            97 => 
            array (
                'brand_id' => NULL,
                'category_id' => '20',
                'code' => NULL,
                'created_at' => '2022-01-21 13:31:31',
                'deleted_at' => NULL,
                'description' => '90 x90 L',
                'dimension_depth' => '1',
                'dimension_height' => '1',
                'dimension_width' => '1',
                'display_price' => '65000',
                'id' => '98',
                'images' => '["/products//tiang_hordeng.jpg"]',
                'name' => 'tiang hordeng',
                'price' => '65000',
                'stock' => '0',
                'updated_at' => '2022-01-21 13:31:31',
                'weight' => '1400',
            ),
        ));
        
        
    }
}