<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TransactionDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('transaction_details')->delete();
        
        \DB::table('transaction_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 2,
                'transaction_id' => 1,
                'name' => 'testing 2',
                'qty' => 2,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-06 08:20:06',
                'updated_at' => '2021-12-06 08:20:06',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 3,
                'transaction_id' => 1,
                'name' => 'Gambar',
                'qty' => 1,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-06 08:20:06',
                'updated_at' => '2021-12-06 08:20:06',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'product_id' => 2,
                'transaction_id' => 2,
                'name' => 'testing 2',
                'qty' => 2,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-06 08:50:46',
                'updated_at' => '2021-12-06 08:50:46',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'product_id' => 3,
                'transaction_id' => 2,
                'name' => 'Gambar',
                'qty' => 1,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-06 08:50:46',
                'updated_at' => '2021-12-06 08:50:46',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'product_id' => 1,
                'transaction_id' => 2,
                'name' => 'TEST ITEM',
                'qty' => 11,
                'price' => 50000.0,
                'weight' => 500.0,
                'width' => 20.0,
                'height' => 30.0,
                'depth' => 2.0,
                'created_at' => '2021-12-06 08:50:46',
                'updated_at' => '2021-12-06 08:50:46',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'product_id' => 1,
                'transaction_id' => 3,
                'name' => 'TEST ITEM',
                'qty' => 1,
                'price' => 50000.0,
                'weight' => 500.0,
                'width' => 20.0,
                'height' => 30.0,
                'depth' => 2.0,
                'created_at' => '2021-12-09 08:43:48',
                'updated_at' => '2021-12-09 08:43:48',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'product_id' => 3,
                'transaction_id' => 4,
                'name' => 'Gambar',
                'qty' => 2,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-09 15:36:30',
                'updated_at' => '2021-12-09 15:36:30',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'product_id' => 2,
                'transaction_id' => 5,
                'name' => 'testing 2',
                'qty' => 2,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:19:17',
                'updated_at' => '2021-12-11 18:19:17',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'product_id' => 3,
                'transaction_id' => 5,
                'name' => 'Gambar',
                'qty' => 2,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:19:17',
                'updated_at' => '2021-12-11 18:19:17',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'product_id' => 2,
                'transaction_id' => 6,
                'name' => 'testing 2',
                'qty' => 4,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:19:56',
                'updated_at' => '2021-12-11 18:19:56',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'product_id' => 3,
                'transaction_id' => 6,
                'name' => 'Gambar',
                'qty' => 2,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:19:56',
                'updated_at' => '2021-12-11 18:19:56',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'product_id' => 2,
                'transaction_id' => 7,
                'name' => 'testing 2',
                'qty' => 4,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:20:24',
                'updated_at' => '2021-12-11 18:20:24',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'product_id' => 3,
                'transaction_id' => 7,
                'name' => 'Gambar',
                'qty' => 2,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:20:24',
                'updated_at' => '2021-12-11 18:20:24',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'product_id' => 2,
                'transaction_id' => 8,
                'name' => 'testing 2',
                'qty' => 4,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:20:46',
                'updated_at' => '2021-12-11 18:20:46',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'product_id' => 3,
                'transaction_id' => 8,
                'name' => 'Gambar',
                'qty' => 2,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:20:46',
                'updated_at' => '2021-12-11 18:20:46',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'product_id' => 2,
                'transaction_id' => 9,
                'name' => 'testing 2',
                'qty' => 4,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:21:41',
                'updated_at' => '2021-12-11 18:21:41',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'product_id' => 3,
                'transaction_id' => 9,
                'name' => 'Gambar',
                'qty' => 20,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:21:41',
                'updated_at' => '2021-12-11 18:21:41',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'product_id' => 1,
                'transaction_id' => 10,
                'name' => 'TEST ITEM',
                'qty' => 1,
                'price' => 50000.0,
                'weight' => 500.0,
                'width' => 20.0,
                'height' => 30.0,
                'depth' => 2.0,
                'created_at' => '2021-12-11 18:26:18',
                'updated_at' => '2021-12-11 18:26:18',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'product_id' => 3,
                'transaction_id' => 10,
                'name' => 'Gambar',
                'qty' => 1,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:26:18',
                'updated_at' => '2021-12-11 18:26:18',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'product_id' => 2,
                'transaction_id' => 10,
                'name' => 'testing 2',
                'qty' => 3,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:26:18',
                'updated_at' => '2021-12-11 18:26:18',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'product_id' => 1,
                'transaction_id' => 11,
                'name' => 'TEST ITEM',
                'qty' => 1,
                'price' => 50000.0,
                'weight' => 500.0,
                'width' => 20.0,
                'height' => 30.0,
                'depth' => 2.0,
                'created_at' => '2021-12-11 18:26:23',
                'updated_at' => '2021-12-11 18:26:23',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'product_id' => 3,
                'transaction_id' => 11,
                'name' => 'Gambar',
                'qty' => 1,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:26:23',
                'updated_at' => '2021-12-11 18:26:23',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'product_id' => 2,
                'transaction_id' => 11,
                'name' => 'testing 2',
                'qty' => 3,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:26:23',
                'updated_at' => '2021-12-11 18:26:23',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'product_id' => 1,
                'transaction_id' => 12,
                'name' => 'TEST ITEM',
                'qty' => 1,
                'price' => 50000.0,
                'weight' => 500.0,
                'width' => 20.0,
                'height' => 30.0,
                'depth' => 2.0,
                'created_at' => '2021-12-11 18:26:26',
                'updated_at' => '2021-12-11 18:26:26',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'product_id' => 3,
                'transaction_id' => 12,
                'name' => 'Gambar',
                'qty' => 1,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:26:26',
                'updated_at' => '2021-12-11 18:26:26',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'product_id' => 2,
                'transaction_id' => 12,
                'name' => 'testing 2',
                'qty' => 3,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:26:26',
                'updated_at' => '2021-12-11 18:26:26',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'product_id' => 1,
                'transaction_id' => 13,
                'name' => 'TEST ITEM',
                'qty' => 1,
                'price' => 50000.0,
                'weight' => 500.0,
                'width' => 20.0,
                'height' => 30.0,
                'depth' => 2.0,
                'created_at' => '2021-12-11 18:26:29',
                'updated_at' => '2021-12-11 18:26:29',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'product_id' => 3,
                'transaction_id' => 13,
                'name' => 'Gambar',
                'qty' => 1,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:26:29',
                'updated_at' => '2021-12-11 18:26:29',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'product_id' => 2,
                'transaction_id' => 13,
                'name' => 'testing 2',
                'qty' => 3,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:26:29',
                'updated_at' => '2021-12-11 18:26:29',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'product_id' => 1,
                'transaction_id' => 14,
                'name' => 'TEST ITEM',
                'qty' => 1,
                'price' => 50000.0,
                'weight' => 500.0,
                'width' => 20.0,
                'height' => 30.0,
                'depth' => 2.0,
                'created_at' => '2021-12-11 18:26:31',
                'updated_at' => '2021-12-11 18:26:31',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'product_id' => 3,
                'transaction_id' => 14,
                'name' => 'Gambar',
                'qty' => 1,
                'price' => 25000.0,
                'weight' => 100.0,
                'width' => 500.0,
                'height' => 2000.0,
                'depth' => 1.0,
                'created_at' => '2021-12-11 18:26:31',
                'updated_at' => '2021-12-11 18:26:31',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'product_id' => 2,
                'transaction_id' => 14,
                'name' => 'testing 2',
                'qty' => 3,
                'price' => 150000.0,
                'weight' => 1.0,
                'width' => 12.0,
                'height' => 21.0,
                'depth' => 3.0,
                'created_at' => '2021-12-11 18:26:31',
                'updated_at' => '2021-12-11 18:26:31',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}