<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TransactionDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('transaction_details')->delete();
        
        \DB::table('transaction_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 3,
                'transaction_id' => 1,
                'name' => 'Shower tiang toto tx 493 srs',
                'qty' => 1,
                'price' => 4300000.0,
                'weight' => 1000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-02 13:38:47',
                'updated_at' => '2022-02-02 13:38:47',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 2,
                'transaction_id' => 1,
                'name' => 'Shower tiang tx 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-02 13:38:47',
                'updated_at' => '2022-02-02 13:38:47',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'product_id' => 4,
                'transaction_id' => 1,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 2,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-02 13:38:47',
                'updated_at' => '2022-02-02 13:38:47',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'product_id' => 4,
                'transaction_id' => 2,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 4,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-05 17:42:43',
                'updated_at' => '2022-02-05 17:42:43',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'product_id' => 5,
                'transaction_id' => 2,
                'name' => 'Kran bath tub tx 47 srsn',
                'qty' => 6,
                'price' => 1820000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-05 17:42:43',
                'updated_at' => '2022-02-05 17:42:43',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'product_id' => 6,
                'transaction_id' => 2,
                'name' => 'Shower tiang toto 492 srs',
                'qty' => 2,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-05 17:42:43',
                'updated_at' => '2022-02-05 17:42:43',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'product_id' => 4,
                'transaction_id' => 3,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 2,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-15 17:40:47',
                'updated_at' => '2022-02-15 17:40:47',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'product_id' => 2,
                'transaction_id' => 4,
                'name' => 'Shower tiang tx 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-18 19:35:46',
                'updated_at' => '2022-02-18 19:35:46',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'product_id' => 3,
                'transaction_id' => 4,
                'name' => 'Shower tiang toto tx 493 srs',
                'qty' => 1,
                'price' => 4300000.0,
                'weight' => 1000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-18 19:35:46',
                'updated_at' => '2022-02-18 19:35:46',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'product_id' => 4,
                'transaction_id' => 4,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 2,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-18 19:35:46',
                'updated_at' => '2022-02-18 19:35:46',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'product_id' => 4,
                'transaction_id' => 5,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 1,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:38:54',
                'updated_at' => '2022-02-24 14:38:54',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'product_id' => 5,
                'transaction_id' => 5,
                'name' => 'Kran bath tub tx 47 srsn',
                'qty' => 1,
                'price' => 1820000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:38:54',
                'updated_at' => '2022-02-24 14:38:54',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'product_id' => 6,
                'transaction_id' => 5,
                'name' => 'Shower tiang toto 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:38:54',
                'updated_at' => '2022-02-24 14:38:54',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'product_id' => 2,
                'transaction_id' => 5,
                'name' => 'Shower tiang tx 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:38:54',
                'updated_at' => '2022-02-24 14:38:54',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'product_id' => 3,
                'transaction_id' => 5,
                'name' => 'Shower tiang toto tx 493 srs',
                'qty' => 1,
                'price' => 4300000.0,
                'weight' => 1000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:38:54',
                'updated_at' => '2022-02-24 14:38:54',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'product_id' => 4,
                'transaction_id' => 6,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 1,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:39:08',
                'updated_at' => '2022-02-24 14:39:08',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'product_id' => 5,
                'transaction_id' => 6,
                'name' => 'Kran bath tub tx 47 srsn',
                'qty' => 1,
                'price' => 1820000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:39:08',
                'updated_at' => '2022-02-24 14:39:08',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'product_id' => 6,
                'transaction_id' => 6,
                'name' => 'Shower tiang toto 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:39:08',
                'updated_at' => '2022-02-24 14:39:08',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'product_id' => 2,
                'transaction_id' => 6,
                'name' => 'Shower tiang tx 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:39:08',
                'updated_at' => '2022-02-24 14:39:08',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'product_id' => 3,
                'transaction_id' => 6,
                'name' => 'Shower tiang toto tx 493 srs',
                'qty' => 1,
                'price' => 4300000.0,
                'weight' => 1000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:39:08',
                'updated_at' => '2022-02-24 14:39:08',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'product_id' => 4,
                'transaction_id' => 7,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 1,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:40:14',
                'updated_at' => '2022-02-24 14:40:14',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'product_id' => 5,
                'transaction_id' => 7,
                'name' => 'Kran bath tub tx 47 srsn',
                'qty' => 1,
                'price' => 1820000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:40:14',
                'updated_at' => '2022-02-24 14:40:14',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'product_id' => 6,
                'transaction_id' => 7,
                'name' => 'Shower tiang toto 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:40:14',
                'updated_at' => '2022-02-24 14:40:14',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'product_id' => 2,
                'transaction_id' => 7,
                'name' => 'Shower tiang tx 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:40:14',
                'updated_at' => '2022-02-24 14:40:14',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'product_id' => 3,
                'transaction_id' => 7,
                'name' => 'Shower tiang toto tx 493 srs',
                'qty' => 1,
                'price' => 4300000.0,
                'weight' => 1000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-02-24 14:40:14',
                'updated_at' => '2022-02-24 14:40:14',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'product_id' => 4,
                'transaction_id' => 8,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 5,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-01 12:48:41',
                'updated_at' => '2022-03-01 12:48:41',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'product_id' => 5,
                'transaction_id' => 8,
                'name' => 'Kran bath tub tx 47 srsn',
                'qty' => 1,
                'price' => 1820000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-01 12:48:41',
                'updated_at' => '2022-03-01 12:48:41',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'product_id' => 6,
                'transaction_id' => 8,
                'name' => 'Shower tiang toto 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-01 12:48:41',
                'updated_at' => '2022-03-01 12:48:41',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'product_id' => 2,
                'transaction_id' => 8,
                'name' => 'Shower tiang tx 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-01 12:48:41',
                'updated_at' => '2022-03-01 12:48:41',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'product_id' => 3,
                'transaction_id' => 8,
                'name' => 'Shower tiang toto tx 493 srs',
                'qty' => 2,
                'price' => 4300000.0,
                'weight' => 1000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-01 12:48:41',
                'updated_at' => '2022-03-01 12:48:41',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'product_id' => 4,
                'transaction_id' => 9,
                'name' => 'Kran shower toto tx 474 srsn',
                'qty' => 1,
                'price' => 1500000.0,
                'weight' => 2000.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-02 10:02:31',
                'updated_at' => '2022-03-02 10:02:31',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'product_id' => 5,
                'transaction_id' => 9,
                'name' => 'Kran bath tub tx 47 srsn',
                'qty' => 1,
                'price' => 1820000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-02 10:02:31',
                'updated_at' => '2022-03-02 10:02:31',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'product_id' => 2,
                'transaction_id' => 10,
                'name' => 'Shower tiang tx 492 srs',
                'qty' => 1,
                'price' => 4200000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-02 10:11:13',
                'updated_at' => '2022-03-02 10:11:13',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'product_id' => 5,
                'transaction_id' => 10,
                'name' => 'Kran bath tub tx 47 srsn',
                'qty' => 1,
                'price' => 1820000.0,
                'weight' => 2500.0,
                'width' => 1.0,
                'height' => 1.0,
                'depth' => 1.0,
                'created_at' => '2022-03-02 10:11:13',
                'updated_at' => '2022-03-02 10:11:13',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'product_id' => 99,
                'transaction_id' => 11,
                'name' => 'TESTING JAKARTA 2',
                'qty' => 1,
                'price' => 200000.0,
                'weight' => 500.0,
                'width' => 500.0,
                'height' => 21.0,
                'depth' => 1.0,
                'created_at' => '2022-03-02 22:37:20',
                'updated_at' => '2022-03-02 22:37:20',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}